const questionPool = [
  { question: "Which king of Judah had his eyes put out after seeing his sons slain at Riblah?", options: ["Zedekiah", "Jehoiachin", "Jehoiakim", "Amon"], answer: "Zedekiah" },
  { question: "What was the name of the high priest's servant whose ear Peter cut off in Gethsemane?", options: ["Malchus", "Marcus", "Mahlon", "Meneras"], answer: "Malchus" },
  { question: "Which prophet was instructed to go to the potter's house to see a vessel being reworked?", options: ["Jeremiah", "Isaiah", "Ezekiel", "Amos"], answer: "Jeremiah" },
  { question: "Who was the father of King Ahab, known for building the city of Samaria?", options: ["Omri", "Baasha", "Jeroboam", "Zimri"], answer: "Omri" },
  { question: "In Revelation, what is the name of the star that fell on the third part of the rivers, making them bitter?", options: ["Wormwood", "Morning Star", "Arcturus", "Orion"], answer: "Wormwood" },
  { question: "Which city's wall fell down flat after Israel compassed it seven times on the seventh day?", options: ["Jericho", "Ai", "Gibeon", "Hazor"], answer: "Jericho" },
  { question: "How many silver pieces did each lord of the Philistines promise Delilah to betray Samson?", options: ["1100 each", "500 each", "300 each", "1000 each"], answer: "1100 each" },
  { question: "Who was the first person to see and speak to the risen Christ near the tomb?", options: ["Mary Magdalene", "Peter", "John", "Mary the mother of James"], answer: "Mary Magdalene" },
  { question: "What specific wood was Noah commanded to use to build the Ark?", options: ["Gopher", "Cedar", "Acacia", "Shittim"], answer: "Gopher" },
  { question: "Which of the seven churches of Asia was rebuked for being neither cold nor hot?", options: ["Laodicea", "Sardis", "Philadelphia", "Ephesus"], answer: "Laodicea" },
  { question: "Who was the scribe that read the Book of the Law to the people after the wall was rebuilt?", options: ["Ezra", "Nehemiah", "Zerubbabel", "Haggai"], answer: "Ezra" },
  { question: "On which island was the apostle John exiled when he received the Revelation?", options: ["Patmos", "Crete", "Malta", "Cyprus"], answer: "Patmos" },
  { question: "Which judge of Israel made a rash vow involving the first thing that came out of his house?", options: ["Jephthah", "Gideon", "Samson", "Barak"], answer: "Jephthah" },
  { question: "What was the original name of the apostle Peter before Jesus called him?", options: ["Simon", "Andrew", "Saul", "Levi"], answer: "Simon" },
  { question: "Which prophet was carried to heaven in a whirlwind by a chariot of fire?", options: ["Elijah", "Elisha", "Enoch", "Isaiah"], answer: "Elijah" },
  { question: "Who was the queen that visited King Solomon to test him with hard questions?", options: ["Queen of Sheba", "Queen Jezebel", "Queen Esther", "Queen Athaliah"], answer: "Queen of Sheba" },
  { question: "In the parable of the Sower, what happened to the seed that fell among thorns?", options: ["It was choked", "It withered", "Birds ate it", "It grew deep roots"], answer: "It was choked" },
  { question: "Which son of David led a rebellion and was caught by his hair in a terebinth tree?", options: ["Absalom", "Adonijah", "Amnon", "Solomon"], answer: "Absalom" },
  { question: "What was the name of the woman who hid the two spies in Jericho?", options: ["Rahab", "Ruth", "Deborah", "Jael"], answer: "Rahab" },
  { question: "Which apostle was a tentmaker by trade, similar to Aquila and Priscilla?", options: ["Paul", "Peter", "James", "Matthew"], answer: "Paul" },
  // You can keep adding more here in the future!
    // BATCH 2: ELITE KNOWLEDGE (Questions 21 - 120)
  { question: "Which king of Israel was known for his 'furious' chariot driving?", options: ["Jehu", "Ahab", "Joram", "Baasha"], answer: "Jehu" },
  { question: "What was the name of the valley where David fought Goliath?", options: ["Valley of Elah", "Valley of Jezreel", "Valley of Berakah", "Valley of Hinnom"], answer: "Valley of Elah" },
  { question: "Who was the father of 12 princes and 12 tribes of Ishmaelites?", options: ["Ishmael", "Hagar", "Nebajoth", "Kedar"], answer: "Ishmael" },
  { question: "What was the name of the place where the sun stood still for nearly a whole day?", options: ["Gibeon", "Aijalon", "Jericho", "Hazor"], answer: "Gibeon" },
  { question: "Which tribe of Israel was not given a portion of land as an inheritance, for the Lord was their inheritance?", options: ["Levi", "Benjamin", "Simeon", "Dan"], answer: "Levi" },
  { question: "Who was the only female judge mentioned in the Book of Judges?", options: ["Deborah", "Jael", "Athaliah", "Huldah"], answer: "Deborah" },
  { question: "How many elders sat around the throne in the vision of Revelation?", options: ["Twenty-four", "Twelve", "Seventy", "Seven"], answer: "Twenty-four" },
  { question: "Which king of Babylon was driven from men and ate grass like oxen?", options: ["Nebuchadnezzar", "Belshazzar", "Evil-merodach", "Nabonidus"], answer: "Nebuchadnezzar" },
  { question: "What was the name of the high priest who charged Jesus with blasphemy?", options: ["Caiaphas", "Annas", "Gamaliel", "Tertullus"], answer: "Caiaphas" },
  { question: "In the vision of Ezekiel, what was the valley full of that came to life?", options: ["Dry bones", "Scorpions", "Burning coals", "Dead cedars"], answer: "Dry bones" },
  { question: "Which man was lowered through a roof by his four friends to be healed by Jesus?", options: ["A paralytic", "A blind man", "Lazarus", "Bartimaeus"], answer: "A paralytic" },
  { question: "What was the occupation of the apostle Luke?", options: ["Physician", "Tax collector", "Fisherman", "Tentmaker"], answer: "Physician" },
  { question: "Who was the first king of the Northern Kingdom of Israel after the split?", options: ["Jeroboam I", "Rehoboam", "Omri", "Jehu"], answer: "Jeroboam I" },
  { question: "What was the name of the mountain where the Ark of Noah rested?", options: ["Ararat", "Sinai", "Nebo", "Carmel"], answer: "Ararat" },
  { question: "Which prophet ran faster than a chariot from Carmel to Jezreel after it rained?", options: ["Elijah", "Elisha", "Samuel", "Nathan"], answer: "Elijah" },
  { question: "What did the soldiers place on Jesus' head during His trial?", options: ["Crown of thorns", "Purple robe", "Reed", "Gold diadem"], answer: "Crown of thorns" },
  { question: "How many stones did David pick up from the brook before facing Goliath?", options: ["Five", "One", "Seven", "Three"], answer: "Five" },
  { question: "Which disciple was known as 'The Twin' (Didymus)?", options: ["Thomas", "Philip", "James the Less", "Matthew"], answer: "Thomas" },
  { question: "Who was the sister of Moses and Aaron who led the women in song?", options: ["Miriam", "Zipporah", "Jochebed", "Elisheba"], answer: "Miriam" },
  { question: "What was the name of the city where the followers of Jesus were first called Christians?", options: ["Antioch", "Jerusalem", "Damascus", "Ephesus"], answer: "Antioch" },
  { question: "Which king of Judah was struck with leprosy for trying to burn incense in the temple?", options: ["Uzziah", "Ahaz", "Hezekiah", "Josiah"], answer: "Uzziah" },
  { question: "What was the name of the garden where Jesus prayed before His arrest?", options: ["Gethsemane", "Eden", "Sharon", "Carmel"], answer: "Gethsemane" },
  { question: "Which man was forced to carry the cross for Jesus?", options: ["Simon of Cyrene", "Joseph of Arimathea", "Nicodemus", "Barabbas"], answer: "Simon of Cyrene" },
  { question: "In Acts, who was the first Gentile convert to Christianity?", options: ["Cornelius", "The Ethiopian Eunuch", "Lydia", "The Philippian Jailer"], answer: "Cornelius" },
  { question: "What was the name of the sea where Jesus calmed the storm?", options: ["Sea of Galilee", "Dead Sea", "Red Sea", "Mediterranean Sea"], answer: "Sea of Galilee" },
  { question: "Who was the mother of Solomon?", options: ["Bathsheba", "Abigail", "Michal", "Maacah"], answer: "Bathsheba" },
  { question: "Which prophet was swallowed by a great fish when fleeing to Tarshish?", options: ["Jonah", "Micah", "Habakkuk", "Zephaniah"], answer: "Jonah" },
  { question: "How many times did Peter deny Jesus before the rooster crowed?", options: ["Three", "Two", "Seven", "One"], answer: "Three" },
  { question: "What was the name of the servant girl who recognized Peter's voice at the gate?", options: ["Rhoda", "Tabitha", "Lydia", "Damaris"], answer: "Rhoda" },
  { question: "Who was the Roman governor who washed his hands during Jesus' trial?", options: ["Pontius Pilate", "Herod Antipas", "Felix", "Festus"], answer: "Pontius Pilate" },
  { question: "Which son of Jacob was the ancestor of the priestly line?", options: ["Levi", "Judah", "Reuben", "Joseph"], answer: "Levi" },
  { question: "What was the name of the food God provided for the Israelites in the wilderness?", options: ["Manna", "Quail", "Locusts", "Honey"], answer: "Manna" },
  { question: "Who was the youngest son of Jesse who became King of Israel?", options: ["David", "Eliab", "Abinadab", "Shammah"], answer: "David" },
  { question: "Which apostle was a brother to John and was killed by Herod with a sword?", options: ["James", "Peter", "Andrew", "Philip"], answer: "James" },
  { question: "What was the name of the idol the Israelites built while Moses was on Sinai?", options: ["Golden Calf", "Baal", "Asherah", "Dagon"], answer: "Golden Calf" },
  { question: "Who was the elderly priest that raised Samuel in the temple?", options: ["Eli", "Phinehas", "Hophni", "Zadok"], answer: "Eli" },
  { question: "Which city did God destroy with fire and brimstone because of its wickedness?", options: ["Sodom", "Nineveh", "Tyre", "Sidon"], answer: "Sodom" },
  { question: "Who was the first man created according to Genesis?", options: ["Adam", "Seth", "Cain", "Abel"], answer: "Adam" },
  { question: "What was the name of the giant Philistine defeated by David?", options: ["Goliath", "Ishbi-benob", "Saph", "Lahmi"], answer: "Goliath" },
  { question: "How many disciples did Jesus choose as His inner circle apostles?", options: ["Twelve", "Seventy", "Three", "Five"], answer: "Twelve" },
  { question: "Who was the wife of Isaac and mother of Jacob and Esau?", options: ["Rebekah", "Rachel", "Leah", "Sarah"], answer: "Rebekah" },
  { question: "What was the name of the mountain where Moses received the Ten Commandments?", options: ["Mount Sinai", "Mount Horeb", "Mount Nebo", "Mount Zion"], answer: "Mount Sinai" },
  { question: "Which disciple was a former tax collector before following Jesus?", options: ["Matthew", "Thomas", "Bartholomew", "Simon the Zealot"], answer: "Matthew" },
  { question: "What was the name of the beautiful queen who saved her people from Haman?", options: ["Esther", "Vashti", "Athaliah", "Jezebel"], answer: "Esther" },
  { question: "Who was the man that survived being thrown into a den of lions?", options: ["Daniel", "Shadrach", "Meshach", "Abednego"], answer: "Daniel" },
  { question: "What instrument did David play to soothe King Saul?", options: ["Harp (Lyre)", "Flute", "Trumpet", "Cymbal"], answer: "Harp (Lyre)" },
  { question: "Which city is known as the 'City of David'?", options: ["Jerusalem", "Bethlehem", "Nazareth", "Hebron"], answer: "Jerusalem" },
  { question: "Who was the prophet that lived in the wilderness and baptized Jesus?", options: ["John the Baptist", "Elijah", "Malachi", "John the Apostle"], answer: "John the Baptist" },
  { question: "How many books are in the New Testament?", options: ["Twenty-seven", "Thirty-nine", "Sixty-six", "Twelve"], answer: "Twenty-seven" },
  { question: "Which book tells the story of the Israelites' escape from Egypt?", options: ["Exodus", "Genesis", "Leviticus", "Numbers"], answer: "Exodus" },
  { question: "Who was the man known for his great patience despite losing everything?", options: ["Job", "Abraham", "Noah", "Lot"], answer: "Job" },
  { question: "What was the sign of God's covenant with Noah after the flood?", options: ["Rainbow", "Circumcision", "Sabbath", "Cloud"], answer: "Rainbow" },
  { question: "Which apostle was blinded on the road to Damascus?", options: ["Paul (Saul)", "Peter", "Barnabas", "Stephen"], answer: "Paul (Saul)" },
  { question: "Who was the mother of John the Baptist?", options: ["Elizabeth", "Mary", "Anna", "Martha"], answer: "Elizabeth" },
  { question: "What was the last book written in the Bible?", options: ["Revelation", "Jude", "Malachi", "Hebrews"], answer: "Revelation" },
  { question: "Which prophet was mocked by youths and two bears came out of the woods?", options: ["Elisha", "Elijah", "Samuel", "Amos"], answer: "Elisha" },
  { question: "Who were the three men thrown into the fiery furnace?", options: ["Shadrach, Meshach, Abednego", "Daniel, Hananiah, Azariah", "Peter, James, John", "Paul, Silas, Timothy"], answer: "Shadrach, Meshach, Abednego" },
  { question: "How many years did the Israelites wander in the wilderness?", options: ["Forty", "Ten", "Seven", "One hundred"], answer: "Forty" },
  { question: "What was the name of the place where Jesus was crucified?", options: ["Golgotha", "Gethsemane", "Bethany", "Emmaus"], answer: "Golgotha" },
  { question: "Who was the leader of the Israelites after Moses died?", options: ["Joshua", "Caleb", "Aaron", "Eleazar"], answer: "Joshua" },
  { question: "Which disciple was known for doubting Jesus' resurrection until he saw Him?", options: ["Thomas", "Philip", "Andrew", "Simon"], answer: "Thomas" },
  { question: "What was the name of the city where Jesus was born?", options: ["Bethlehem", "Nazareth", "Jerusalem", "Jericho"], answer: "Bethlehem" },
  { question: "Who was the father of many nations and the husband of Sarah?", options: ["Abraham", "Isaac", "Jacob", "Terah"], answer: "Abraham" },
  { question: "Which book of the Bible contains the most chapters?", options: ["Psalms", "Isaiah", "Genesis", "Jeremiah"], answer: "Psalms" },
  { question: "What did Joseph's brothers do with him after throwing him in a pit?", options: ["Sold him to Ishmaelites", "Left him to die", "Brought him back home", "Killed him"], answer: "Sold him to Ishmaelites" },
  { question: "Who was the strong man whose hair was the secret to his strength?", options: ["Samson", "Goliath", "Saul", "Benaiah"], answer: "Samson" },
  { question: "What was the first miracle performed by Jesus?", options: ["Turning water into wine", "Healing a leper", "Feeding the 5000", "Walking on water"], answer: "Turning water into wine" },
  { question: "Who was the woman that discovered Jesus had risen on the first day?", options: ["Mary Magdalene", "Martha", "Lydia", "Dorcas"], answer: "Mary Magdalene" },
  { question: "How many days and nights did it rain during the Great Flood?", options: ["Forty", "Seven", "Twelve", "One hundred"], answer: "Forty" },
  { question: "Which prophet spoke about the 'Suffering Servant' in chapter 53?", options: ["Isaiah", "Jeremiah", "Daniel", "Joel"], answer: "Isaiah" },
  { question: "Who was the wise king who built the first Temple in Jerusalem?", options: ["Solomon", "David", "Hezekiah", "Josiah"], answer: "Solomon" },
  { question: "What is the shortest verse in the Bible?", options: ["Jesus wept.", "Rejoice evermore.", "God is love.", "Pray without ceasing."], answer: "Jesus wept." },
  { question: "Which animal spoke to Balaam after he beat it three times?", options: ["Donkey", "Snake", "Lion", "Lamb"], answer: "Donkey" },
  { question: "Who was the man that climbed a sycamore tree to see Jesus?", options: ["Zacchaeus", "Lazarus", "Nicodemus", "Bartimaeus"], answer: "Zacchaeus" },
  { question: "What was the primary language of the Old Testament?", options: ["Hebrew", "Greek", "Latin", "Aramaic"], answer: "Hebrew" },
  { question: "Who was the wife of King Ahab who incited him to do evil?", options: ["Jezebel", "Athaliah", "Herodias", "Vashti"], answer: "Jezebel" },
  { question: "How many people were fed with five loaves and two fish?", options: ["5,000 men", "3,000 people", "12,000 men", "1,000 people"], answer: "5,000 men" },
  { question: "Which book of the Bible follows the Gospels?", options: ["Acts", "Romans", "Galatians", "Hebrews"], answer: "Acts" },
  { question: "Who were the first two disciples called by Jesus?", options: ["Peter and Andrew", "James and John", "Philip and Nathanael", "Matthew and Thomas"], answer: "Peter and Andrew" },
  { question: "What was the name of the river where Jesus was baptized?", options: ["Jordan", "Nile", "Euphrates", "Tigris"], answer: "Jordan" },
  { question: "Who was the cousin of Jesus born six months before Him?", options: ["John the Baptist", "James", "Jude", "Lazarus"], answer: "John the Baptist" },
  { question: "What was the first plague God sent upon Egypt?", options: ["Water into blood", "Frogs", "Lice", "Darkness"], answer: "Water into blood" },
  { question: "Which king of Persia allowed the Jews to return and rebuild the temple?", options: ["Cyrus", "Darius", "Artaxerxes", "Xerxes"], answer: "Cyrus" },
  { question: "Who was the man that died after touching the Ark of the Covenant?", options: ["Uzzah", "Obed-edom", "Abinadab", "Ahio"], answer: "Uzzah" },
  { question: "What was the name of the woman who judged Israel under a palm tree?", options: ["Deborah", "Miriam", "Hannah", "Huldah"], answer: "Deborah" },
  { question: "Which apostle was shipwrecked on the island of Malta?", options: ["Paul", "Peter", "John", "Barnabas"], answer: "Paul" },
  { question: "What was the name of the city where the walls fell after being circled?", options: ["Jericho", "Ai", "Gibeon", "Bethel"], answer: "Jericho" },
  { question: "Who was the Roman centurion that Peter visited in Caesarea?", options: ["Cornelius", "Julius", "Longinus", "Marcus"], answer: "Cornelius" },
  { question: "What was the name of the mountain where Elijah faced the prophets of Baal?", options: ["Mount Carmel", "Mount Sinai", "Mount Hermon", "Mount Tabor"], answer: "Mount Carmel" },
  { question: "Who was the man from Arimathea who buried Jesus in his own tomb?", options: ["Joseph", "Nicodemus", "Simon", "Lazarus"], answer: "Joseph" },
  { question: "What was the name of the sorcerer who tried to buy the power of the Holy Spirit?", options: ["Simon", "Elymas", "Bar-Jesus", "Theudas"], answer: "Simon" },
  { question: "Which book of the Bible is known for its poetic expressions of love?", options: ["Song of Solomon", "Proverbs", "Ecclesiastes", "Lamentations"], answer: "Song of Solomon" },
  { question: "Who was the father of John the Baptist?", options: ["Zechariah", "Simeon", "Joachim", "Annas"], answer: "Zechariah" },
  { question: "What was the name of the place where Jacob had his dream of a ladder?", options: ["Bethel", "Peniel", "Shechem", "Beersheba"], answer: "Bethel" },
  { question: "Which apostle was formerly known as Levi the son of Alphaeus?", options: ["Matthew", "Thomas", "James the Less", "Jude"], answer: "Matthew" },
  { question: "Who was the sister of Lazarus and Mary who was busy with housework?", options: ["Martha", "Tabitha", "Lydia", "Salome"], answer: "Martha" },
  { question: "What was the name of the king who sought to kill the baby Jesus?", options: ["Herod the Great", "Herod Antipas", "Herod Agrippa", "Augustus"], answer: "Herod the Great" },
  { question: "Which man was caught up to the third heaven, as mentioned in 2 Corinthians?", options: ["Paul", "John", "Peter", "Stephen"], answer: "Paul" },
  { question: "What was the name of the slave for whom Paul wrote the book of Philemon?", options: ["Onesimus", "Tychicus", "Epaphras", "Demas"], answer: "Onesimus" },
  { question: "Which animal did Noah send out first from the Ark?", options: ["Raven", "Dove", "Sparrow", "Eagle"], answer: "Raven" },
     // BATCH 3: THE EPISTLES & DEEP PROPHETS (Questions 121 - 220)
  { question: "Which book of the Bible explicitly mentions the 'Archangel Michael' contending for the body of Moses?", options: ["Jude", "Revelation", "2 Peter", "Hebrews"], answer: "Jude" },
  { question: "What was the name of the goldsmith who led the riot against Paul in Ephesus?", options: ["Demetrius", "Alexander", "Sosthenes", "Tyrannus"], answer: "Demetrius" },
  { question: "Who was the first person Jesus raised from the dead in the presence of a crowd at the city of Nain?", options: ["A widow's son", "Lazarus", "Jairus' daughter", "Tabitha"], answer: "A widow's son" },
  { question: "Which prophet had a vision of a 'wheel within a wheel' by the River Chebar?", options: ["Ezekiel", "Daniel", "Isaiah", "Zechariah"], answer: "Ezekiel" },
  { question: "In the book of Acts, which couple was struck dead for withholding part of their land's profit?", options: ["Ananias and Sapphira", "Aquila and Priscilla", "Andronicus and Junia", "Philemon and Apphia"], answer: "Ananias and Sapphira" },
  { question: "How many months was Moses hidden by his mother before she placed him in the ark of bulrushes?", options: ["Three months", "One month", "Six months", "Two months"], answer: "Three months" },
  { question: "What was the name of the mountain where King Saul and his sons died in battle?", options: ["Mount Gilboa", "Mount Tabor", "Mount Hermon", "Mount Carmel"], answer: "Mount Gilboa" },
  { question: "To which city was the apostle Paul traveling when he saw the great light and heard Jesus' voice?", options: ["Damascus", "Jerusalem", "Antioch", "Tarsus"], answer: "Damascus" },
  { question: "Who was the mother of Timothy, mentioned by Paul for her 'unfeigned faith'?", options: ["Eunice", "Lois", "Lydia", "Phoebe"], answer: "Eunice" },
  { question: "Which judge slew 600 Philistines with an ox goad?", options: ["Shamgar", "Gideon", "Tola", "Ibzan"], answer: "Shamgar" },
  { question: "What was the name of the place where the Israelites camped and found twelve wells of water and seventy palm trees?", options: ["Elim", "Marah", "Rephidim", "Sinai"], answer: "Elim" },
  { question: "Who was the King of Salem and Priest of the Most High God who blessed Abraham?", options: ["Melchizedek", "Abimelech", "Chedorlaomer", "Potiphar"], answer: "Melchizedek" },
  { question: "In the Parable of the Ten Virgins, how many were described as 'wise'?", options: ["Five", "Three", "Seven", "Ten"], answer: "Five" },
  { question: "Which book of the Bible ends with the word 'Amen'?", options: ["Revelation", "Jude", "3 John", "Malachi"], answer: "Revelation" },
  { question: "What was the name of the city where the followers of Jesus were first called 'Christians'?", options: ["Antioch", "Damascus", "Jerusalem", "Rome"], answer: "Antioch" },
  { question: "Who was the father of King David?", options: ["Jesse", "Eliab", "Boaz", "Obed"], answer: "Jesse" },
  { question: "How many years did Jacob work for Laban in total to marry Rachel and Leah?", options: ["Fourteen", "Seven", "Twenty", "Ten"], answer: "Fourteen" },
  { question: "What was the name of the woman who hid the spies in Jericho and was saved from the city's destruction?", options: ["Rahab", "Ruth", "Deborah", "Michal"], answer: "Rahab" },
  { question: "Which disciple was a former tax collector?", options: ["Matthew", "Thomas", "Simon", "Andrew"], answer: "Matthew" },
  { question: "Who was the King of Israel after Saul?", options: ["David", "Solomon", "Ish-bosheth", "Jonathan"], answer: "David" },
  { question: "What was the name of the place where Jesus performed His first miracle?", options: ["Cana", "Nazareth", "Capernaum", "Bethsaida"], answer: "Cana" },
  { question: "Which prophet was thrown into a lion's den during the reign of Darius?", options: ["Daniel", "Ezekiel", "Amos", "Haggai"], answer: "Daniel" },
  { question: "What did God use to symbolize His promise to never flood the earth again?", options: ["A rainbow", "A cloud", "A dove", "A pillar of fire"], answer: "A rainbow" },
  { question: "How many days was Jonah inside the great fish?", options: ["Three", "Seven", "Forty", "Twelve"], answer: "Three" },
  { question: "Which queen went to visit Solomon to test him with hard questions?", options: ["Queen of Sheba", "Queen Vashti", "Queen Jezebel", "Queen Esther"], answer: "Queen of Sheba" },
  { question: "Who was the first person to see the risen Christ?", options: ["Mary Magdalene", "Peter", "John", "Mary (Mother of Jesus)"], answer: "Mary Magdalene" },
  { question: "Which book of the Bible contains the verse: 'The Lord is my shepherd; I shall not want'?", options: ["Psalms", "Proverbs", "Isaiah", "Genesis"], answer: "Psalms" },
  { question: "What was the name of the giant Philistine David defeated?", options: ["Goliath", "Saph", "Lahmi", "Ishbi-benob"], answer: "Goliath" },
  { question: "How many people were saved on Noah's Ark?", options: ["Eight", "Two", "Twelve", "Seven"], answer: "Eight" },
  { question: "Who was the brother of Moses?", options: ["Aaron", "Joshua", "Caleb", "Hur"], answer: "Aaron" },
  { question: "What was the occupation of the apostle Peter before following Jesus?", options: ["Fisherman", "Tax collector", "Tentmaker", "Physician"], answer: "Fisherman" },
  { question: "Which city is known as the 'City of David'?", options: ["Bethlehem", "Jerusalem", "Nazareth", "Hebron"], answer: "Bethlehem" },
  { question: "Who was the man who survived the fiery furnace with Shadrach and Meshach?", options: ["Abednego", "Daniel", "Darius", "Nebuchadnezzar"], answer: "Abednego" },
  { question: "What is the shortest book in the Old Testament?", options: ["Obadiah", "Joel", "Haggai", "Malachi"], answer: "Obadiah" },
  { question: "Who was the priest of Midian and father-in-law of Moses?", options: ["Jethro", "Laban", "Potipherah", "Melchizedek"], answer: "Jethro" },
  { question: "What did the Israelites eat in the wilderness?", options: ["Manna and Quail", "Bread and Fish", "Honey and Locusts", "Figs and Olives"], answer: "Manna and Quail" },
  { question: "Which apostle was blinded on the road to Damascus?", options: ["Saul (Paul)", "Peter", "Barnabas", "Stephen"], answer: "Saul (Paul)" },
  { question: "Who was the sister of Lazarus and Mary?", options: ["Martha", "Ruth", "Elizabeth", "Salome"], answer: "Martha" },
  { question: "How many books are in the New Testament?", options: ["27", "39", "66", "12"], answer: "27" },
  { question: "Who wrote the first five books of the Old Testament?", options: ["Moses", "David", "Solomon", "Samuel"], answer: "Moses" },
  { question: "Which disciple was known as the 'Beloved Disciple'?", options: ["John", "Peter", "James", "Andrew"], answer: "John" },
  { question: "What was the first plague God sent upon Egypt?", options: ["Blood", "Frogs", "Lice", "Darkness"], answer: "Blood" },
  { question: "Which prophet was carried to heaven in a whirlwind?", options: ["Elijah", "Elisha", "Enoch", "Isaiah"], answer: "Elijah" },
  { question: "Who was the mother of John the Baptist?", options: ["Elizabeth", "Mary", "Hannah", "Sarah"], answer: "Elizabeth" },
  { question: "What was the last word in the Old Testament?", options: ["Curse", "Amen", "Lord", "Promise"], answer: "Curse" },
  { question: "Which man climbed a sycamore tree to see Jesus?", options: ["Zacchaeus", "Lazarus", "Nicodemus", "Bartimaeus"], answer: "Zacchaeus" },
  { question: "How many years did the Israelites wander in the wilderness?", options: ["Forty", "Ten", "Seven", "One hundred"], answer: "Forty" },
  { question: "Who was the woman who discovered Jesus had risen?", options: ["Mary Magdalene", "Martha", "Lydia", "Dorcas"], answer: "Mary Magdalene" },
  { question: "Which son of David rebelled and was caught by his hair in a tree?", options: ["Absalom", "Adonijah", "Solomon", "Amnon"], answer: "Absalom" },
  { question: "What was the name of the river Jesus was baptized in?", options: ["Jordan", "Nile", "Euphrates", "Tigris"], answer: "Jordan" },
  { question: "Who was the youngest son of Jacob?", options: ["Benjamin", "Joseph", "Reuben", "Dan"], answer: "Benjamin" },
  { question: "Which book of the Bible contains the story of a woman named Esther?", options: ["Esther", "Ruth", "Judith", "Song of Solomon"], answer: "Esther" },
  { question: "What was the primary language of the New Testament?", options: ["Greek", "Hebrew", "Latin", "Aramaic"], answer: "Greek" },
  { question: "Who was the man known for his great wisdom and for building the Temple?", options: ["Solomon", "David", "Hezekiah", "Josiah"], answer: "Solomon" },
  { question: "How many tribes of Israel were there?", options: ["Twelve", "Ten", "Seven", "Forty"], answer: "Twelve" },
  { question: "Who was the woman that was turned into a pillar of salt?", options: ["Lot's Wife", "Sarah", "Rebekah", "Hagar"], answer: "Lot's Wife" },
  { question: "Which disciple was a twin (Didymus)?", options: ["Thomas", "Philip", "Andrew", "James"], answer: "Thomas" },
  { question: "What was the name of the place where Jesus was crucified?", options: ["Golgotha", "Gethsemane", "Bethany", "Emmaus"], answer: "Golgotha" },
  { question: "Who was the father of Abraham?", options: ["Terah", "Nahor", "Haran", "Lot"], answer: "Terah" },
  { question: "Which apostle wrote the book of Romans?", options: ["Paul", "Peter", "John", "James"], answer: "Paul" },
  { question: "What was the name of the high priest who presided over Jesus' trial?", options: ["Caiaphas", "Annas", "Gamaliel", "Tertullus"], answer: "Caiaphas" },
  { question: "Who was the man who had his strength in his hair?", options: ["Samson", "Goliath", "Absalom", "Benaiah"], answer: "Samson" },
  { question: "Which book tells the story of the Israelites leaving Egypt?", options: ["Exodus", "Genesis", "Numbers", "Leviticus"], answer: "Exodus" },
  { question: "What was the name of the mountain where Moses received the Law?", options: ["Mount Sinai", "Mount Nebo", "Mount Zion", "Mount Carmel"], answer: "Mount Sinai" },
  { question: "Who was the cousin of Jesus who preached in the wilderness?", options: ["John the Baptist", "James", "Jude", "Lazarus"], answer: "John the Baptist" },
  { question: "How many disciples did Jesus have?", options: ["Twelve", "Seventy", "Three", "Five"], answer: "Twelve" },
  { question: "Who was the wife of Abraham?", options: ["Sarah", "Hagar", "Keturah", "Rebekah"], answer: "Sarah" },
  { question: "What was the name of the garden where Jesus was arrested?", options: ["Gethsemane", "Eden", "Sharon", "Carmel"], answer: "Gethsemane" },
  { question: "Who was the first king of Israel?", options: ["Saul", "David", "Solomon", "Samuel"], answer: "Saul" },
  { question: "How many commandments did God give Moses on Sinai?", options: ["Ten", "Twelve", "Seven", "Three"], answer: "Ten" },
  { question: "Who was the man that climbed the sycamore tree?", options: ["Zacchaeus", "Bartimaeus", "Lazarus", "Simon"], answer: "Zacchaeus" },
  { question: "What is the longest chapter in the Bible?", options: ["Psalm 119", "Psalm 23", "Isaiah 53", "Genesis 1"], answer: "Psalm 119" },
  { question: "Who was the woman who gave birth to Jesus?", options: ["Mary", "Elizabeth", "Anna", "Martha"], answer: "Mary" },
  { question: "Which apostle was shipwrecked on Malta?", options: ["Paul", "Peter", "Barnabas", "John"], answer: "Paul" },
  { question: "What did David use to kill Goliath?", options: ["A sling and a stone", "A sword", "A spear", "A bow and arrow"], answer: "A sling and a stone" },
  { question: "Who was the man that lived for 969 years?", options: ["Methuselah", "Enoch", "Noah", "Adam"], answer: "Methuselah" },
  { question: "Which prophet was swallowed by a great fish?", options: ["Jonah", "Amos", "Micah", "Joel"], answer: "Jonah" },
  { question: "What was the first miracle of Jesus?", options: ["Water to wine", "Healing the blind", "Walking on water", "Raising Lazarus"], answer: "Water to wine" },
  { question: "Who was the man that denied Jesus three times?", options: ["Peter", "Judas", "Thomas", "Andrew"], answer: "Peter" },
  { question: "How many books are in the Bible?", options: ["66", "72", "39", "27"], answer: "66" },
  { question: "What was the name of the city where walls fell down?", options: ["Jericho", "Jerusalem", "Bethlehem", "Nazareth"], answer: "Jericho" },
  { question: "Who was the strong man deceived by Delilah?", options: ["Samson", "Gideon", "Saul", "Barak"], answer: "Samson" },
  { question: "Who was the mother of Samuel?", options: ["Hannah", "Peninnah", "Eli", "Sarah"], answer: "Hannah" },
  { question: "What was the name of the man who sold his birthright for soup?", options: ["Esau", "Jacob", "Isaac", "Ishmael"], answer: "Esau" },
  { question: "Which book contains the verse: 'For God so loved the world...'?", options: ["John", "Matthew", "Luke", "Mark"], answer: "John" },
  { question: "How many days and nights did it rain during Noah's flood?", options: ["Forty", "Seven", "Twelve", "One hundred"], answer: "Forty" },
  { question: "Who was the apostle who took the gospel to the Gentiles?", options: ["Paul", "Peter", "James", "Jude"], answer: "Paul" },
  { question: "What was the name of the sea Moses parted?", options: ["Red Sea", "Dead Sea", "Sea of Galilee", "Mediterranean Sea"], answer: "Red Sea" },
  { question: "Who was the man that survived being thrown into a den of lions?", options: ["Daniel", "Shadrach", "Meshach", "Abednego"], answer: "Daniel" },
  { question: "What was the name of the woman who lived in the house in Jericho?", options: ["Rahab", "Ruth", "Deborah", "Jael"], answer: "Rahab" },
  { question: "Who was the prophet that challenged the prophets of Baal on Mount Carmel?", options: ["Elijah", "Elisha", "Samuel", "Isaiah"], answer: "Elijah" },
  { question: "What is the fruit of the Spirit, according to Galatians?", options: ["Love, Joy, Peace...", "Faith, Hope, Charity", "Wisdom, Power, Might", "Gold, Frankincense, Myrrh"], answer: "Love, Joy, Peace..." },
  { question: "How many people were fed with 5 loaves and 2 fish?", options: ["5,000 men", "3,000", "12,000", "1,000"], answer: "5,000 men" },
  { question: "Who was the high priest who raised Samuel?", options: ["Eli", "Samuel", "Aaron", "Zadok"], answer: "Eli" },
  { question: "Which book comes after the four Gospels?", options: ["Acts", "Romans", "Hebrews", "Revelation"], answer: "Acts" },
  { question: "Who was the first Christian martyr?", options: ["Stephen", "James", "Peter", "Paul"], answer: "Stephen" },
  { question: "What was the name of the king of Persia in the book of Esther?", options: ["Ahasuerus (Xerxes)", "Cyrus", "Darius", "Artaxerxes"], answer: "Ahasuerus (Xerxes)" },
  { question: "Who was the cousin of Jesus born to Elizabeth?", options: ["John the Baptist", "James", "Jude", "Andrew"], answer: "John the Baptist" },
  { question: "What is the final book of the Bible?", options: ["Revelation", "Jude", "3 John", "Malachi"], answer: "Revelation" },
  { question: "How many plagues did God send on Egypt?", options: ["Ten", "Twelve", "Seven", "Three"], answer: "Ten" },
  // BATCH 4: DEEP SCRIPTURE & GEOGRAPHY (Questions 221 - 320)
  { question: "Which king of Israel was killed by an arrow shot 'at a venture' (at random) between the joints of his harness?", options: ["Ahab", "Jehoram", "Josiah", "Ahaziah"], answer: "Ahab" },
  { question: "According to the book of Judges, which man killed 1,000 Philistines with the jawbone of a donkey?", options: ["Samson", "Shamgar", "Gideon", "Othniel"], answer: "Samson" },
  { question: "What was the name of the place where Abraham was prepared to sacrifice Isaac?", options: ["Mount Moriah", "Mount Sinai", "Mount Nebo", "Mount Gerizim"], answer: "Mount Moriah" },
  { question: "Who was the father of the prophet Samuel?", options: ["Elkanah", "Eli", "Ichabod", "Kish"], answer: "Elkanah" },
  { question: "In the book of Acts, who was the silversmith in Ephesus who started a riot against Paul?", options: ["Demetrius", "Alexander", "Sosthenes", "Tyrannus"], answer: "Demetrius" },
  { question: "Which tribe of Israel was specifically omitted from the list of the 144,000 in Revelation 7?", options: ["Dan", "Manasseh", "Simeon", "Asher"], answer: "Dan" },
  { question: "What was the name of the wood used for the Ark of the Covenant?", options: ["Shittim (Acacia)", "Gopher", "Cedar", "Olive"], answer: "Shittim (Acacia)" },
  { question: "How many months was Moses hidden by his mother before she put him in the Nile?", options: ["Three", "Six", "One", "Two"], answer: "Three" },
  { question: "Who was the Roman governor of Judea when Jesus was born?", options: ["Quirinius", "Pontius Pilate", "Felix", "Festus"], answer: "Quirinius" },
  { question: "What was the name of the servant girl who recognized Peter’s voice at the gate of Mary's house?", options: ["Rhoda", "Tabitha", "Lydia", "Phoebe"], answer: "Rhoda" },
  { question: "Which minor prophet was commanded to marry an unfaithful woman named Gomer?", options: ["Hosea", "Amos", "Joel", "Obadiah"], answer: "Hosea" },
  { question: "What was the name of the city that Nimrod built in the land of Shinar?", options: ["Babel", "Nineveh", "Ur", "Sodom"], answer: "Babel" },
  { question: "Who was the prophet that rebuked King David for his sin with Bathsheba using a parable of a rich man and a lamb?", options: ["Nathan", "Samuel", "Gad", "Elijah"], answer: "Nathan" },
  { question: "Which son of Jacob was the father of the two tribes Ephraim and Manasseh?", options: ["Joseph", "Levi", "Benjamin", "Judah"], answer: "Joseph" },
  { question: "In the tabernacle, what was the specific metal used for the sockets of the pillars of the court?", options: ["Brass", "Gold", "Silver", "Iron"], answer: "Brass" },
  { question: "What was the name of the king of Israel who reigned for only seven days?", options: ["Zimri", "Shallum", "Zechariah", "Pekahiah"], answer: "Zimri" },
  { question: "Who was the left-handed judge who killed Eglon, king of Moab?", options: ["Ehud", "Othniel", "Shamgar", "Jair"], answer: "Ehud" },
  { question: "What was the name of the sea where the disciples were fishing when Jesus appeared to them after His resurrection?", options: ["Sea of Tiberias", "Dead Sea", "Sea of Jazer", "Red Sea"], answer: "Sea of Tiberias" },
  { question: "Which king of Judah was only eight years old when he began to reign and did what was right in the eyes of the Lord?", options: ["Josiah", "Uzziah", "Hezekiah", "Manasseh"], answer: "Josiah" },
  { question: "Who was the father of John the Baptist and belonged to the priestly division of Abijah?", options: ["Zechariah", "Simeon", "Nicodemus", "Annas"], answer: "Zechariah" },
  { question: "In the vision of the four beasts in Daniel 7, which beast represented the Grecian empire?", options: ["Leopard", "Lion", "Bear", "Terrible beast"], answer: "Leopard" },
  { question: "What was the name of the valley where the sun stood still for Joshua?", options: ["Valley of Aijalon", "Valley of Elah", "Valley of Jezreel", "Valley of Hinnom"], answer: "Valley of Aijalon" },
  { question: "Who was the grandmother of Timothy, mentioned for her faith?", options: ["Lois", "Eunice", "Lydia", "Priscilla"], answer: "Lois" },
  { question: "What was the first of the seven churches addressed in the Book of Revelation?", options: ["Ephesus", "Smyrna", "Pergamum", "Sardis"], answer: "Ephesus" },
  { question: "Which king of Judah saw his sons killed before his eyes and then had his own eyes put out?", options: ["Zedekiah", "Jehoiachin", "Jehoiakim", "Manasseh"], answer: "Zedekiah" },
  { question: "Who was the first woman judge (prophetess) mentioned in the Bible who sat under a palm tree?", options: ["Deborah", "Jael", "Huldah", "Noadiah"], answer: "Deborah" },
  { question: "What was the name of the altar that the tribes of Reuben and Gad built by the Jordan?", options: ["Ed", "Bethel", "Gilgal", "Mizpah"], answer: "Ed" },
  { question: "Who was the scribe that read the Law of Moses to the people from a wooden pulpit?", options: ["Ezra", "Nehemiah", "Zerubbabel", "Haggai"], answer: "Ezra" },
  { question: "In Revelation 9, what was the name of the angel of the bottomless pit in Hebrew?", options: ["Abaddon", "Apollyon", "Beelzebub", "Belial"], answer: "Abaddon" },
  { question: "What was the specific material used to build the walls of the New Jerusalem in Revelation 21?", options: ["Jasper", "Gold", "Sapphire", "Emerald"], answer: "Jasper" },
  { question: "Who was the high priest who charged Paul with sedition and being a ringleader of the Nazarenes?", options: ["Ananias", "Caiaphas", "Annas", "Gamaliel"], answer: "Ananias" },
  { question: "How many silver pieces did each lord of the Philistines offer Delilah to betray Samson?", options: ["1,100", "500", "300", "1,000"], answer: "1,100" },
  { question: "Which man was caught by his long hair in an oak tree during a battle against his father David?", options: ["Absalom", "Adonijah", "Amnon", "Solomon"], answer: "Absalom" },
  { question: "What was the name of the place where Jacob wrestled with a man until daybreak?", options: ["Peniel", "Bethel", "Shechem", "Succoth"], answer: "Peniel" },
  { question: "Which apostle was known as 'The Twin'?", options: ["Thomas", "Philip", "Bartholomew", "Andrew"], answer: "Thomas" },
  { question: "What was the name of the mountain where Elijah had the showdown with 450 prophets of Baal?", options: ["Mount Carmel", "Mount Sinai", "Mount Horeb", "Mount Hermon"], answer: "Mount Carmel" },
  { question: "Who was the king of Persia who issued a decree for the Jews to rebuild the temple?", options: ["Cyrus", "Darius", "Xerxes", "Artaxerxes"], answer: "Cyrus" },
  { question: "Which minor prophet is the only one recorded as being a 'herdsman and a gatherer of sycamore fruit'?", options: ["Amos", "Micah", "Joel", "Haggai"], answer: "Amos" },
  { question: "In the book of Acts, who was the first Christian martyr to be stoned to death?", options: ["Stephen", "James", "Peter", "Antipas"], answer: "Stephen" },
  { question: "What was the name of the island where Paul was shipwrecked on his way to Rome?", options: ["Malta", "Crete", "Cyprus", "Rhodes"], answer: "Malta" },
  { question: "Which king of Israel reigned for forty years and was known for his extreme wisdom?", options: ["Solomon", "David", "Saul", "Hezekiah"], answer: "Solomon" },
  { question: "How many pieces of silver was Joseph sold for by his brothers?", options: ["Twenty", "Thirty", "Fifty", "Ten"], answer: "Twenty" },
  { question: "Who was the man who took over the role of apostle after Judas Iscariot?", options: ["Matthias", "Barnabas", "Joseph Barsabbas", "Silas"], answer: "Matthias" },
  { question: "In Ezekiel’s vision, what was the valley full of that eventually came back to life?", options: ["Dry bones", "Dead cedars", "Thorns", "Scorpions"], answer: "Dry bones" },
  { question: "What was the name of the city where the followers of Jesus were first called 'Christians'?", options: ["Antioch", "Damascus", "Jerusalem", "Rome"], answer: "Antioch" },
  { question: "Which queen of Judah seized the throne and tried to destroy the entire royal family?", options: ["Athaliah", "Jezebel", "Vashti", "Bernice"], answer: "Athaliah" },
  { question: "Who was the father of King Ahab?", options: ["Omri", "Baasha", "Zimri", "Jeroboam"], answer: "Omri" },
  { question: "In the book of Revelation, what was the color of the horse whose rider’s name was Death?", options: ["Pale", "Red", "Black", "White"], answer: "Pale" },
  { question: "How many times did the Israelites compass the city of Jericho on the seventh day?", options: ["Seven", "One", "Twelve", "Three"], answer: "Seven" },
  { question: "Which of the apostles was a tentmaker by trade?", options: ["Paul", "Peter", "Matthew", "John"], answer: "Paul" },
  { question: "What was the name of the sorcerer in Paphos who was blinded by Paul for opposing the gospel?", options: ["Elymas", "Simon Magus", "Theudas", "Alexander"], answer: "Elymas" },
  { question: "Who was the mother of King Solomon?", options: ["Bathsheba", "Michal", "Abigail", "Maacah"], answer: "Bathsheba" },
  { question: "What was the name of the wood used to build Noah's Ark?", options: ["Gopher", "Cedar", "Oak", "Cypress"], answer: "Gopher" },
  { question: "In the parable of the Sower, which ground represented people who hear the word but the cares of this world choke it?", options: ["Among thorns", "Stony ground", "Way side", "Good ground"], answer: "Among thorns" },
  { question: "Who was the prophet that saw a vision of a valley of dry bones?", options: ["Ezekiel", "Jeremiah", "Isaiah", "Daniel"], answer: "Ezekiel" },
  { question: "What was the name of the high priest who raised Samuel in the temple at Shiloh?", options: ["Eli", "Phinehas", "Hophni", "Zadok"], answer: "Eli" },
  { question: "Which of the seven churches was told they had 'left their first love'?", options: ["Ephesus", "Sardis", "Laodicea", "Smyrna"], answer: "Ephesus" },
  { question: "Who was the man that built the first city mentioned in the Bible, naming it after his son Enoch?", options: ["Cain", "Adam", "Seth", "Lamech"], answer: "Cain" },
  { question: "How many years did the Jews spend in Babylonian captivity?", options: ["Seventy", "Forty", "Four hundred", "Fifty"], answer: "Seventy" },
  { question: "What was the name of the river where John the Baptist baptized Jesus?", options: ["Jordan", "Nile", "Abana", "Pharpar"], answer: "Jordan" },
  { question: "Which book of the Bible follows the book of Daniel?", options: ["Hosea", "Amos", "Joel", "Ezekiel"], answer: "Hosea" },
  { question: "Who was the woman who Judged Israel while sitting under a palm tree?", options: ["Deborah", "Miriam", "Ruth", "Huldah"], answer: "Deborah" },
  { question: "What was the original name of the city of Bethel before Jacob renamed it?", options: ["Luz", "Salem", "Hebron", "Shechem"], answer: "Luz" },
  { question: "Who was the father of Gershom and Eliezer?", options: ["Moses", "Aaron", "Joshua", "Joseph"], answer: "Moses" },
  { question: "What was the specific count of the fish caught by the disciples in John 21?", options: ["153", "144", "120", "50"], answer: "153" },
  { question: "Which king of Judah was struck with leprosy because he tried to offer incense in the Temple?", options: ["Uzziah", "Hezekiah", "Josiah", "Ahaz"], answer: "Uzziah" },
  { question: "What was the name of the place where God confused the language of the people?", options: ["Babel", "Nineveh", "Ur", "Gomorrah"], answer: "Babel" },
  { question: "Which apostle was exiled to the island of Patmos?", options: ["John", "Paul", "Peter", "Andrew"], answer: "John" },
  { question: "Who was the first king of the Northern Kingdom of Israel after the split?", options: ["Jeroboam", "Rehoboam", "Omri", "Jehu"], answer: "Jeroboam" },
  { question: "What was the name of the servant girl who recognize Peter's voice at the gate?", options: ["Rhoda", "Mary", "Tabitha", "Lydia"], answer: "Rhoda" },
  { question: "Who was the man that died for touching the Ark of the Covenant when it stumbled?", options: ["Uzzah", "Ahio", "Abinadab", "Obed-edom"], answer: "Uzzah" },
  { question: "In the book of Esther, what was the name of the king's official who plotted to kill the Jews?", options: ["Haman", "Mordecai", "Memucan", "Bigthan"], answer: "Haman" },
  { question: "What was the name of the mountain where Noah's Ark came to rest?", options: ["Mount Ararat", "Mount Sinai", "Mount Nebo", "Mount Carmel"], answer: "Mount Ararat" },
  { question: "Which prophet was thrown into a miry dungeon during the siege of Jerusalem?", options: ["Jeremiah", "Isaiah", "Ezekiel", "Zechariah"], answer: "Jeremiah" },
  { question: "Who was the father of the twelve princes and twelve tribes of the Ishmaelites?", options: ["Ishmael", "Nebajoth", "Kedar", "Adbeel"], answer: "Ishmael" },
  { question: "How many times did Jesus tell Peter to forgive his brother?", options: ["Seventy times seven", "Seven times", "Three times", "Ten times"], answer: "Seventy times seven" },
  { question: "What was the name of the high priest's servant whose ear Peter cut off?", options: ["Malchus", "Marcus", "Mahlon", "Meneras"], answer: "Malchus" },
  { question: "Who was the Roman governor who washed his hands during the trial of Jesus?", options: ["Pontius Pilate", "Herod", "Felix", "Festus"], answer: "Pontius Pilate" },
  { question: "Which book of the Bible is the shortest?", options: ["3 John", "Obadiah", "2 John", "Jude"], answer: "3 John" },
  { question: "Who was the mother of Samuel who prayed for a child in the temple?", options: ["Hannah", "Peninnah", "Elizabeth", "Sarah"], answer: "Hannah" },
  { question: "What was the name of the valley where David fought Goliath?", options: ["Valley of Elah", "Valley of Jezreel", "Valley of Berakah", "Valley of Hinnom"], answer: "Valley of Elah" },
  { question: "Which judge was asked by God to reduce his army from 32,000 to 300 men?", options: ["Gideon", "Barak", "Samson", "Jephthah"], answer: "Gideon" },
  { question: "Who was the king of Salem and priest of God who met Abraham after the battle?", options: ["Melchizedek", "Abimelech", "Potiphar", "Jethro"], answer: "Melchizedek" },
  { question: "In the parable of the Ten Virgins, how many were wise?", options: ["Five", "Three", "Seven", "Ten"], answer: "Five" },
  { question: "Who was the father of King Saul?", options: ["Kish", "Abner", "Ner", "Jesse"], answer: "Kish" },
  { question: "What was the name of the beautiful woman who was the wife of Nabal and later King David?", options: ["Abigail", "Bathsheba", "Michal", "Maacah"], answer: "Abigail" },
  { question: "Which of the four Gospels was written by a doctor?", options: ["Luke", "Matthew", "Mark", "John"], answer: "Luke" },
  { question: "What was the name of the first man born to Adam and Eve?", options: ["Cain", "Abel", "Seth", "Enos"], answer: "Cain" },
  { question: "How many silver pieces did Judas receive for betraying Jesus?", options: ["Thirty", "Twenty", "Fifty", "Ten"], answer: "Thirty" },
  { question: "Who was the Roman emperor when Jesus was born?", options: ["Augustus", "Tiberius", "Nero", "Caligula"], answer: "Augustus" },
  { question: "What was the name of the place where Jesus was crucified?", options: ["Golgotha", "Gethsemane", "Bethany", "Emmaus"], answer: "Golgotha" },
  { question: "Who was the woman who hid the spies in Jericho?", options: ["Rahab", "Ruth", "Deborah", "Jael"], answer: "Rahab" },
  { question: "How many books are in the New Testament?", options: ["Twenty-seven", "Thirty-nine", "Sixty-six", "Twelve"], answer: "Twenty-seven" },
  { question: "Who was the apostle who took the gospel to the Gentiles?", options: ["Paul", "Peter", "James", "Jude"], answer: "Paul" },
  { question: "What was the name of the sea that Moses parted?", options: ["Red Sea", "Dead Sea", "Sea of Galilee", "Mediterranean Sea"], answer: "Red Sea" },
  { question: "Who was the man that survived being thrown into a den of lions?", options: ["Daniel", "Shadrach", "Meshach", "Abednego"], answer: "Daniel" },
  { question: "Who was the prophet that challenged the prophets of Baal on Mount Carmel?", options: ["Elijah", "Elisha", "Samuel", "Isaiah"], answer: "Elijah" },
  { question: "What is the fruit of the Spirit according to Galatians?", options: ["Love, Joy, Peace...", "Faith, Hope, Charity", "Wisdom, Power, Might", "Gold, Frankincense, Myrrh"], answer: "Love, Joy, Peace..." },
  { question: "How many people were fed with 5 loaves and 2 fish?", options: ["5,000 men", "3,000", "12,000", "1,000"], answer: "5,000 men" },
  { question: "Who was the high priest who raised Samuel?", options: ["Eli", "Samuel", "Aaron", "Zadok"], answer: "Eli" },
  // BATCH 5: THE SCHOLAR'S VAULT (Questions 321 - 420)
  { question: "In the book of Hebrews, Jesus is said to be a priest forever after which specific order?", options: ["The order of Melchizedek", "The order of Aaron", "The order of Levi", "The order of Zadok"], answer: "The order of Melchizedek" },
  { question: "Which prophet was told to buy a linen girdle, hide it in a hole of a rock by the Euphrates, and later found it marred?", options: ["Jeremiah", "Ezekiel", "Isaiah", "Habakkuk"], answer: "Jeremiah" },
  { question: "In the book of Galatians, which two women are used as an allegory for two covenants?", options: ["Hagar and Sarah", "Rachel and Leah", "Hannah and Peninnah", "Ruth and Orpah"], answer: "Hagar and Sarah" },
  { question: "Who was the Roman deputy (proconsul) of Cyprus who was converted after seeing Elymas the sorcerer blinded?", options: ["Sergius Paulus", "Cornelius", "Gallio", "Publius"], answer: "Sergius Paulus" },
  { question: "In the vision of the 70 weeks in Daniel, how many weeks were determined upon the people to finish the transgression?", options: ["Seventy weeks", "Seven weeks", "Sixty-two weeks", "Ten weeks"], answer: "Seventy weeks" },
  { question: "Which king of Israel purchased the hill of Samaria from Shemer for two talents of silver?", options: ["Omri", "Ahab", "Jehu", "Baasha"], answer: "Omri" },
  { question: "In the book of Job, which of his friends was the first to speak after the seven days of silence?", options: ["Eliphaz the Temanite", "Bildad the Shuhite", "Zophar the Naamathite", "Elihu the Buzite"], answer: "Eliphaz the Temanite" },
  { question: "Which New Testament book contains the specific warning: 'Even as Sodom and Gomorrha... are set forth for an example'?", options: ["Jude", "2 Peter", "Romans", "Revelation"], answer: "Jude" },
  { question: "What was the name of the high priest who commanded those standing by Paul to smite him on the mouth?", options: ["Ananias", "Caiaphas", "Annas", "Sceva"], answer: "Ananias" },
  { question: "In Revelation, what is the name of the angel of the bottomless pit, also known as 'The Destroyer'?", options: ["Apollyon", "Beelzebub", "Belial", "Lucifer"], answer: "Apollyon" },
  { question: "Which king of Judah removed the high places and broke the brazen serpent that Moses had made?", options: ["Hezekiah", "Josiah", "Asa", "Jehoshaphat"], answer: "Hezekiah" },
  { question: "In the valley of dry bones vision, what did the Lord tell Ezekiel to prophesy unto first?", options: ["The wind", "The bones", "The sinews", "The flesh"], answer: "The wind" },
  { question: "Who was the king of the Amorites that refused to let Israel pass through his border and was subsequently defeated at Jahaz?", options: ["Sihon", "Og", "Balak", "Eglon"], answer: "Sihon" },
  { question: "According to the book of Judges, what was the name of the place where 42,000 Ephraimites were slain because they could not pronounce 'Shibboleth'?", options: ["The passages of Jordan", "The hill of Moreh", "The valley of Jezreel", "The rock of Rimmon"], answer: "The passages of Jordan" },
  { question: "Which prophet had a vision of four chariots coming out from between two mountains of brass?", options: ["Zechariah", "Haggai", "Malachi", "Zephaniah"], answer: "Zechariah" },
  { question: "In 2 Kings, who was the woman that cried 'Treason, Treason' when Joash was crowned king?", options: ["Athaliah", "Jezebel", "Bernice", "Drusilla"], answer: "Athaliah" },
  { question: "What was the name of the city in which Paul was when he had the vision of the 'man of Macedonia'?", options: ["Troas", "Philippi", "Thessalonica", "Berea"], answer: "Troas" },
  { question: "Which king of Israel was known as the son of Nimshi (actually his grandson) and anointed by a young prophet?", options: ["Jehu", "Joram", "Ahab", "Ahaziah"], answer: "Jehu" },
  { question: "In the book of Habakkuk, the prophet stands upon his 'watch' to see what God will say. On what mountain/structure was he?", options: ["The tower", "The wall", "The hill", "The temple"], answer: "The tower" },
  { question: "Who was the father of the four daughters who did prophesy, mentioned in the book of Acts?", options: ["Philip the evangelist", "Stephen", "Barnabas", "Agabus"], answer: "Philip the evangelist" },
  { question: "Which apostle was bit by a viper on the island of Melita but felt no harm?", options: ["Paul", "Peter", "John", "James"], answer: "Paul" },
  { question: "In the book of Malachi, whom does God say He loved, while hating his brother?", options: ["Jacob", "Isaac", "Abel", "David"], answer: "Jacob" },
  { question: "What was the name of the place where the disciples were first called Christians?", options: ["Antioch", "Damascus", "Jerusalem", "Ephesus"], answer: "Antioch" },
  { question: "Which king of Judah was only 8 years old when he began to reign and found the Book of the Law in the temple?", options: ["Josiah", "Uzziah", "Manasseh", "Amon"], answer: "Josiah" },
  { question: "In the vision of Peter, what was the object let down from heaven like a great sheet knit at the four corners?", options: ["A vessel", "A cloud", "A net", "A basket"], answer: "A vessel" },
  { question: "Who was the left-handed judge who delivered Israel from Eglon king of Moab?", options: ["Ehud", "Othniel", "Shamgar", "Tola"], answer: "Ehud" },
  { question: "What was the name of the mountain where Aaron died and was buried?", options: ["Mount Hor", "Mount Sinai", "Mount Nebo", "Mount Pisgah"], answer: "Mount Hor" },
  { question: "Which minor prophet questioned God about why He would use the Chaldeans to punish a people more righteous than they?", options: ["Habakkuk", "Nahum", "Zephaniah", "Obadiah"], answer: "Habakkuk" },
  { question: "In Revelation 1, Jesus is standing in the midst of how many golden candlesticks?", options: ["Seven", "Twelve", "Twenty-four", "One"], answer: "Seven" },
  { question: "Who was the wife of Felix the governor, who was a Jewess and heard Paul speak of faith in Christ?", options: ["Drusilla", "Bernice", "Lydia", "Phoebe"], answer: "Drusilla" },
  { question: "What was the name of the city that Paul and Barnabas were in when they were called Jupiter and Mercurius?", options: ["Lystra", "Derbe", "Iconium", "Paphos"], answer: "Lystra" },
  { question: "Which king of Israel was so wicked that his reign lasted only one month in Samaria?", options: ["Shallum", "Zimri", "Zechariah", "Menahem"], answer: "Shallum" },
  { question: "In the book of Romans, Paul mentions a woman named Phoebe. What was her role in the church at Cenchrea?", options: ["A servant (deaconess)", "A prophetess", "A teacher", "An apostle"], answer: "A servant (deaconess)" },
  { question: "Who was the father of King Saul, whose asses went missing leading to Saul's meeting with Samuel?", options: ["Kish", "Abiel", "Ner", "Zeror"], answer: "Kish" },
  { question: "In the tabernacle, what was the specific wood used for the Ark of the Covenant and the Altars?", options: ["Shittim wood (Acacia)", "Gopher wood", "Cedar wood", "Olive wood"], answer: "Shittim wood (Acacia)" },
  { question: "Which prophet was told to shave his head and beard with a sharp razor and divide the hair into three parts?", options: ["Ezekiel", "Isaiah", "Jeremiah", "Micah"], answer: "Ezekiel" },
  { question: "In the book of Acts, which man was a 'certain sorcerer, a false prophet' whose name was Bar-jesus?", options: ["Elymas", "Simon Magus", "Theudas", "Alexander"], answer: "Elymas" },
  { question: "Who was the king of Tyre who sent cedar trees, carpenters, and masons to build David a house?", options: ["Hiram", "Abimelech", "Ethbaal", "Ben-hadad"], answer: "Hiram" },
  { question: "In the book of James, who is cited as an example of faith because she received the messengers and sent them out another way?", options: ["Rahab", "Ruth", "Deborah", "Sarah"], answer: "Rahab" },
  { question: "Which book of the Bible follows the book of Philemon?", options: ["Hebrews", "Hebrews", "Titus", "1 Peter"], answer: "Hebrews" },
  { question: "What was the name of the place where the sun stood still and the moon stayed until the people had avenged themselves?", options: ["Gibeon and Aijalon", "Jericho", "Beth-horon", "Gilgal"], answer: "Gibeon and Aijalon" },
  { question: "Who was the first person Jesus appeared to after His resurrection according to Mark 16?", options: ["Mary Magdalene", "Peter", "John", "The two disciples on the road"], answer: "Mary Magdalene" },
  { question: "Which judge of Israel made a rash vow that resulted in the sacrifice of his only daughter?", options: ["Jephthah", "Gideon", "Samson", "Ibzan"], answer: "Jephthah" },
  { question: "In the vision of Zechariah, who was standing at the right hand of the Angel of the Lord to resist Joshua the high priest?", options: ["Satan", "Gabriel", "Michael", "The Accuser"], answer: "Satan" },
  { question: "Who was the queen that visited Solomon to test him with hard questions and came with a very great train?", options: ["Queen of Sheba", "Queen of Ethiopia", "Queen Vashti", "Queen Jezebel"], answer: "Queen of Sheba" },
  { question: "In the book of Acts, who was the first person to be raised from the dead by the apostle Peter?", options: ["Tabitha (Dorcas)", "Eutychus", "Aeneas", "Lazarus"], answer: "Tabitha (Dorcas)" },
  { question: "Which king of Israel is described as 'a cake not turned' in the book of Hosea?", options: ["Ephraim", "Judah", "Manasseh", "Gad"], answer: "Ephraim" },
  { question: "Who was the father of Lot?", options: ["Haran", "Terah", "Nahor", "Abraham"], answer: "Haran" },
  { question: "In 1 Corinthians, Paul identifies 'the last enemy' that shall be destroyed. What is it?", options: ["Death", "Satan", "The Flesh", "Sin"], answer: "Death" },
  { question: "What was the name of the brother of Goliath the Gittite, whom Elhanan slew?", options: ["Lahmi", "Saph", "Ishbi-benob", "Goliath"], answer: "Lahmi" },
  { question: "Which prophet spoke of the valley of Jehoshaphat as the place where God would judge the heathen?", options: ["Joel", "Amos", "Micah", "Zephaniah"], answer: "Joel" },
  { question: "In the book of Esther, what was the name of the king's chamberlain who kept the women?", options: ["Hegai", "Hatach", "Harbonah", "Mehuman"], answer: "Hegai" },
  { question: "Who was the man who was called 'the first-born of every creature' in the book of Colossians?", options: ["Jesus Christ", "Adam", "Melchizedek", "Abraham"], answer: "Jesus Christ" },
  { question: "What was the name of the place where Moses struck the rock and water came out, which also means 'temptation'?", options: ["Massah", "Meribah", "Elim", "Rephidim"], answer: "Massah" },
  { question: "Which king of Judah was hiding in Samaria and was slain by the command of Jehu?", options: ["Ahaziah", "Joram", "Jehoash", "Amaziah"], answer: "Ahaziah" },
  { question: "In the book of Daniel, what was the original Hebrew name of the man renamed Abednego?", options: ["Azariah", "Hananiah", "Mishael", "Belteshazzar"], answer: "Azariah" },
  { question: "Who was the wife of Moses?", options: ["Zipporah", "Tharbis", "Elisheba", "Jochebed"], answer: "Zipporah" },
  { question: "In the book of Proverbs, which animal is said to have no guide, overseer, or ruler, yet provideth her meat in the summer?", options: ["The ant", "The coney", "The locust", "The spider"], answer: "The ant" },
  { question: "Which apostle was a citizen of Rome by birth?", options: ["Paul", "Peter", "John", "Matthew"], answer: "Paul" },
  { question: "In the book of Revelation, the New Jerusalem has how many gates?", options: ["Twelve", "Seven", "Three", "Twelve thousand"], answer: "Twelve" },
  { question: "Who was the prophet that rebuked King Ahab for the murder of Naboth?", options: ["Elijah", "Elisha", "Micaiah", "Obadiah"], answer: "Elijah" },
  { question: "In the book of Leviticus, which two sons of Aaron were killed by fire from the Lord for offering strange fire?", options: ["Nadab and Abihu", "Eleazar and Ithamar", "Phinehas and Hophni", "Gershom and Eliezer"], answer: "Nadab and Abihu" },
  { question: "Which city was known as the 'City of Palm Trees'?", options: ["Jericho", "Engedi", "Bethlehem", "Gaza"], answer: "Jericho" },
  { question: "Who was the father of the twelve princes and twelve tribes of the Ishmaelites?", options: ["Ishmael", "Kedar", "Nebajoth", "Adbeel"], answer: "Ishmael" },
  { question: "In the book of Amos, what was the object the prophet saw that symbolised God's judgment?", options: ["A plumbline", "A basket of summer fruit", "A boiling pot", "An almond tree rod"], answer: "A plumbline" },
  { question: "Who was the woman that was turned into a pillar of salt for looking back at Sodom?", options: ["Lot's wife", "Sarah", "Rebekah", "Hagar"], answer: "Lot's wife" },
  { question: "In the book of Acts, which man was 'full of faith and power' and did great wonders before being stoned?", options: ["Stephen", "Philip", "Prochorus", "Nicanor"], answer: "Stephen" },
  { question: "What was the name of the king of Moab who hired Balaam to curse Israel?", options: ["Balak", "Eglon", "Mesha", "Sihon"], answer: "Balak" },
  { question: "Which book of the Bible contains the verse: 'The heart is deceitful above all things, and desperately wicked'?", options: ["Jeremiah", "Proverbs", "Ecclesiastes", "Psalms"], answer: "Jeremiah" },
  { question: "In the book of Judges, what was the name of the woman who killed Sisera with a tent nail?", options: ["Jael", "Deborah", "Rahab", "Michal"], answer: "Jael" },
  { question: "Who was the high priest who charged Jesus with blasphemy during His trial?", options: ["Caiaphas", "Annas", "Ananias", "Simeon"], answer: "Caiaphas" },
  { question: "Which of the four living creatures in Revelation 4 was like a flying eagle?", options: ["The fourth", "The first", "The second", "The third"], answer: "The fourth" },
  { question: "Who was the king of Judah who was carried away to Babylon in fetters of brass after his sons were killed?", options: ["Zedekiah", "Jehoiachin", "Jehoiakim", "Manasseh"], answer: "Zedekiah" },
  { question: "In the book of Numbers, which two men were the only ones from the original generation allowed to enter the Promised Land?", options: ["Joshua and Caleb", "Moses and Aaron", "Eleazar and Ithamar", "Gershon and Kohath"], answer: "Joshua and Caleb" },
  { question: "Which prophet was swallowed by a great fish when he fled to Tarshish?", options: ["Jonah", "Amos", "Micah", "Nahum"], answer: "Jonah" },
  { question: "Who was the man who survived being thrown into a den of lions because he prayed to his God?", options: ["Daniel", "Shadrach", "Meshach", "Abednego"], answer: "Daniel" },
  { question: "In the book of Nehemiah, which two men were the primary mockers and opposers of the rebuilding of the wall?", options: ["Sanballat and Tobiah", "Geshem and Shemaiah", "Haman and Mordecai", "Dathan and Abiram"], answer: "Sanballat and Tobiah" },
  { question: "Which king of Israel reigned for only seven days before burning the palace over himself?", options: ["Zimri", "Shallum", "Zechariah", "Pekah"], answer: "Zimri" },
  { question: "In the book of Acts, who was the woman from Joppa who was full of good works and almsdeeds, and was raised from the dead?", options: ["Tabitha (Dorcas)", "Lydia", "Damaris", "Rhoda"], answer: "Tabitha (Dorcas)" },
  { question: "Who was the king of Babylon when the handwriting appeared on the wall?", options: ["Belshazzar", "Nebuchadnezzar", "Evil-merodach", "Cyrus"], answer: "Belshazzar" },
  { question: "Which minor prophet is the shortest book in the Old Testament?", options: ["Obadiah", "Joel", "Haggai", "Jonah"], answer: "Obadiah" },
  { question: "In the book of Ezekiel, who were the four faces of the living creatures?", options: ["Man, Lion, Ox, Eagle", "Man, Lion, Calf, Eagle", "Man, Lion, Ram, Eagle", "Man, Lion, Lamb, Eagle"], answer: "Man, Lion, Ox, Eagle" },
  { question: "Who was the high priest of Midian and father-in-law of Moses?", options: ["Jethro (Reuel)", "Laban", "Potipherah", "Melchizedek"], answer: "Jethro (Reuel)" },
  { question: "What was the name of the place where Jacob wrestled with an angel and his name was changed to Israel?", options: ["Peniel", "Bethel", "Shechem", "Succoth"], answer: "Peniel" },
  { question: "Which king of Judah was struck with leprosy for attempting to offer incense in the temple?", options: ["Uzziah", "Hezekiah", "Josiah", "Uzziah"], answer: "Uzziah" },
  { question: "In the book of Revelation, the star that falls to earth in the third trumpet is called what?", options: ["Wormwood", "Abaddon", "The Morning Star", "Arcturus"], answer: "Wormwood" },
  { question: "Who was the Roman governor who sent Paul to Rome to be tried by Caesar?", options: ["Festus", "Felix", "Pilate", "Gallio"], answer: "Festus" },
  { question: "Which tribe of Israel received no inheritance of land, for the Lord was their inheritance?", options: ["Levi", "Benjamin", "Simeon", "Dan"], answer: "Levi" },
  { question: "Who was the scribe who assisted the prophet Jeremiah in writing the scroll?", options: ["Baruch", "Ebed-melech", "Seraiah", "Gedaliah"], answer: "Baruch" },
  { question: "What was the name of the valley where David fought and defeated Goliath?", options: ["Valley of Elah", "Valley of Jezreel", "Valley of Hinnom", "Valley of Salt"], answer: "Valley of Elah" },
  { question: "Which apostle was known as 'The Twin'?", options: ["Thomas", "Andrew", "James", "Philip"], answer: "Thomas" },
  { question: "Who was the prophet that lived in the wilderness and prepared the way for the Lord?", options: ["John the Baptist", "Elijah", "Isaiah", "Malachi"], answer: "John the Baptist" },
  { question: "In the book of Genesis, who was the first person to build an altar to the Lord?", options: ["Noah", "Adam", "Cain", "Abraham"], answer: "Noah" },
  { question: "Who was the woman that was a seller of purple from the city of Thyatira, who became a believer in Philippi?", options: ["Lydia", "Phoebe", "Priscilla", "Damaris"], answer: "Lydia" },
  { question: "Which king of Israel was known for his extreme wisdom, wealth, and the building of the first Temple?", options: ["Solomon", "David", "Hezekiah", "Josiah"], answer: "Solomon" },
  { question: "What was the name of the mountain where Moses died and was buried by God?", options: ["Mount Nebo", "Mount Sinai", "Mount Hor", "Mount Carmel"], answer: "Mount Nebo" },
  { question: "Who was the prophet that said, 'But they that wait upon the Lord shall renew their strength'?", options: ["Isaiah", "Jeremiah", "Ezekiel", "Amos"], answer: "Isaiah" },
  { question: "Which son of David rebelled and was killed when his hair got caught in a tree?", options: ["Absalom", "Adonijah", "Amnon", "Solomon"], answer: "Absalom" },
  { question: "In the book of Hebrews, who is described as being without father, without mother, and without descent?", options: ["Melchizedek", "Jesus", "Abraham", "Enoch"], answer: "Melchizedek" },
  { question: "Who was the high priest who raised the child Samuel in the temple?", options: ["Eli", "Phinehas", "Hophni", "Zadok"], answer: "Eli" },
      // BATCH 6: THE HOLY OF HOLIES (Questions 421 - 500)
  { question: "In the book of Zechariah, what was the name of the woman who sat in the midst of the ephah, representing wickedness?", options: ["Wickedness", "Jezebel", "Athaliah", "Gomer"], answer: "Wickedness" },
  { question: "Which king of Judah was given a sign by God where the shadow went backward ten degrees on the dial of Ahaz?", options: ["Hezekiah", "Josiah", "Uzziah", "Asa"], answer: "Hezekiah" },
  { question: "According to the book of Leviticus, which specific bird is listed first among the fowls that shall not be eaten?", options: ["The eagle", "The vulture", "The osprey", "The raven"], answer: "The eagle" },
  { question: "Who was the father of Bezaleel, the chief artisan of the Tabernacle from the tribe of Judah?", options: ["Uri", "Hur", "Caleb", "Amminadab"], answer: "Uri" },
  { question: "In the book of Acts, what was the name of the man at Lystra who had been a cripple from his mother's womb and was healed by Paul?", options: ["A certain man", "Aeneas", "Elymas", "Eutychus"], answer: "A certain man" },
  { question: "Which of the minor prophets described the Lord as 'a jealous God' who 'reserveth wrath for his enemies' in his opening chapter?", options: ["Nahum", "Habakkuk", "Zephaniah", "Malachi"], answer: "Nahum" },
  { question: "What was the name of the king of Gath to whom David fled when he feigned madness?", options: ["Achish", "Abimelech", "Hiram", "Sihon"], answer: "Achish" },
  { question: "In the vision of Revelation 12, how many stars were in the crown of the woman clothed with the sun?", options: ["Twelve", "Seven", "Ten", "Twenty-four"], answer: "Twelve" },
  { question: "Which prophet was told to take a tile and portray upon it the city of Jerusalem and lay siege against it?", options: ["Ezekiel", "Jeremiah", "Isaiah", "Daniel"], answer: "Ezekiel" },
  { question: "What was the name of the mountain where the ten commandments were given, also referred to as the 'Mount of God'?", options: ["Horeb", "Nebo", "Pisgah", "Tabor"], answer: "Horeb" },
  { question: "Who was the king of Israel who reigned in Samaria for two years and died because he fell down through a lattice in his upper chamber?", options: ["Ahaziah", "Joram", "Jehu", "Ahab"], answer: "Ahaziah" },
  { question: "In the parable of the Unjust Steward, for how many measures of oil did the steward tell the debtor to write 'fifty'?", options: ["An hundred", "Eighty", "Seventy", "Sixty"], answer: "An hundred" },
  { question: "Which son of Saul was David's best friend, whose soul was 'knit with the soul of David'?", options: ["Jonathan", "Abinadab", "Malchishua", "Ish-bosheth"], answer: "Jonathan" },
  { question: "In the book of Job, which animal is described as having scales so near to one another that no air can come between them?", options: ["Leviathan", "Behemoth", "The Dragon", "The Serpent"], answer: "Leviathan" },
  { question: "Who was the queen of Persia before Esther, who was deposed for refusing the king's command?", options: ["Vashti", "Athaliah", "Bernice", "Drusilla"], answer: "Vashti" },
  { question: "Which of the twelve apostles was also called 'Nathanael' in the Gospel of John?", options: ["Bartholomew", "Philip", "Thomas", "Thaddaeus"], answer: "Bartholomew" },
  { question: "In the book of Judges, what was the specific name of the place where Gideon built an altar and called it 'Jehovah-shalom'?", options: ["Ophrah", "Bethel", "Gilgal", "Shechem"], answer: "Ophrah" },
  { question: "Who was the prophetess who spoke to the king's officials after the Book of the Law was found in the temple during Josiah's reign?", options: ["Huldah", "Deborah", "Anna", "Miriam"], answer: "Huldah" },
  { question: "What was the specific name of the gate of the temple where the lame man sat and was healed by Peter and John?", options: ["Beautiful", "East", "Sheep", "Golden"], answer: "Beautiful" },
  { question: "Which king of Judah was given fifteen more years of life after he wept and prayed to the Lord?", options: ["Hezekiah", "Josiah", "Manasseh", "Asa"], answer: "Hezekiah" },
  { question: "In the book of Acts, who was the husband of Sapphira?", options: ["Ananias", "Aquila", "Philemon", "Agabus"], answer: "Ananias" },
  { question: "What was the name of the sorcerer who tried to buy the gift of the Holy Spirit from Peter?", options: ["Simon", "Elymas", "Theudas", "Alexander"], answer: "Simon" },
  { question: "Which minor prophet spoke of the 'sun of righteousness' arising with healing in his wings?", options: ["Malachi", "Haggai", "Zechariah", "Joel"], answer: "Malachi" },
  { question: "How many cities of refuge were the Israelites commanded to appoint?", options: ["Six", "Three", "Twelve", "Seven"], answer: "Six" },
  { question: "In the book of Revelation, what is the number of the man (the Beast)?", options: ["666", "777", "144", "12"], answer: "666" },
  { question: "Who was the father of King Josiah?", options: ["Amon", "Manasseh", "Hezekiah", "Ahaz"], answer: "Amon" },
  { question: "What was the name of the place where the disciples were when the Holy Spirit descended on the Day of Pentecost?", options: ["The upper room", "The temple", "Gethsemane", "Solomon's Porch"], answer: "The upper room" },
  { question: "Which apostle was a brother to the apostle Peter?", options: ["Andrew", "James", "John", "Philip"], answer: "Andrew" },
  { question: "In the book of Proverbs, who is the author of the 'words' in the final chapter (Chapter 31)?", options: ["King Lemuel", "Solomon", "Agur", "David"], answer: "King Lemuel" },
  { question: "Who was the first high priest of Israel?", options: ["Aaron", "Moses", "Eleazar", "Phinehas"], answer: "Aaron" },
  { question: "What was the name of the valley where the kings of Sodom and Gomorrah were defeated and fell into slime pits?", options: ["Vale of Siddim", "Valley of Elah", "Valley of Salt", "Valley of Shaveh"], answer: "Vale of Siddim" },
  { question: "In the book of Daniel, who was the king that saw the 'fingers of a man's hand' writing on the wall?", options: ["Belshazzar", "Nebuchadnezzar", "Darius", "Cyrus"], answer: "Belshazzar" },
  { question: "Which of the tribes of Israel was noted for being 'expert in war, with all instruments of war' when they came to David at Hebron?", options: ["Zebulun", "Asher", "Dan", "Naphtali"], answer: "Zebulun" },
  { question: "Who was the man who was 'an eloquent man, and mighty in the scriptures' who came to Ephesus and was instructed by Aquila and Priscilla?", options: ["Apollos", "Timothy", "Titus", "Silas"], answer: "Apollos" },
  { question: "What was the name of the servant girl who recognized Peter's voice at the gate?", options: ["Rhoda", "Tabitha", "Lydia", "Mary"], answer: "Rhoda" },
  { question: "Which king of Israel is famously described as being 'anointed with the horn of oil' by Samuel?", options: ["David", "Saul", "Solomon", "Jehu"], answer: "David" },
  { question: "In the book of Revelation, which church was told they were 'lukewarm' and would be spued out of the Lord's mouth?", options: ["Laodicea", "Sardis", "Philadelphia", "Thyatira"], answer: "Laodicea" },
  { question: "What was the name of the hill in Athens where Paul delivered his famous sermon to the philosophers?", options: ["Mars' Hill (Areopagus)", "Mount Zion", "Mount Hermon", "Mount Moriah"], answer: "Mars' Hill (Areopagus)" },
  { question: "Who was the mother of Ishmael?", options: ["Hagar", "Sarah", "Keturah", "Zilpah"], answer: "Hagar" },
  { question: "In the book of Hebrews, who is the 'author and finisher of our faith'?", options: ["Jesus", "Paul", "God the Father", "The Holy Spirit"], answer: "Jesus" },
  { question: "What was the name of the man who died after lying to Peter about the price of the land he sold?", options: ["Ananias", "Sapphira", "Demas", "Alexander"], answer: "Ananias" },
  { question: "Which prophet was called while he was behind twelve yoke of oxen?", options: ["Elisha", "Elijah", "Amos", "Hosea"], answer: "Elisha" },
  { question: "Who was the woman who became a mother in Israel and defeated the Canaanite general Sisera?", options: ["Deborah", "Jael", "Rahab", "Ruth"], answer: "Deborah" },
  { question: "In the book of Revelation, how many elders were sitting around the throne?", options: ["Twenty-four", "Twelve", "Seven", "Four"], answer: "Twenty-four" },
  { question: "What was the name of the place where the Israelites found the water was too bitter to drink?", options: ["Marah", "Elim", "Rephidim", "Massah"], answer: "Marah" },
  { question: "Who was the man that came to Jesus by night to ask about being born again?", options: ["Nicodemus", "Zacchaeus", "Lazarus", "Joseph of Arimathea"], answer: "Nicodemus" },
  { question: "Which apostle was a tax collector (publican) before Jesus called him?", options: ["Matthew", "Thomas", "Simon", "Bartholomew"], answer: "Matthew" },
  { question: "What was the name of the giant city that Jonah was sent to preach to?", options: ["Nineveh", "Babylon", "Tyre", "Sidon"], answer: "Nineveh" },
  { question: "Who was the king of Judah who was only seven years old when he began to reign and was hidden in the temple for six years?", options: ["Joash", "Josiah", "Uzziah", "Hezekiah"], answer: "Joash" },
  { question: "In the book of Acts, which man was chosen by lot to replace Judas Iscariot?", options: ["Matthias", "Barnabas", "Joseph Barsabbas", "Silas"], answer: "Matthias" },
  { question: "What was the name of the river in Babylon where the captives sat down and wept when they remembered Zion?", options: ["Chebar", "Euphrates", "Tigris", "Jordan"], answer: "Chebar" },
  { question: "Who was the king of Israel who reigned for only seven days?", options: ["Zimri", "Shallum", "Zechariah", "Pekah"], answer: "Zimri" },
  { question: "In the book of Proverbs, who is the woman whose price is 'far above rubies'?", options: ["The virtuous woman", "Wisdom", "Prudence", "The mother"], answer: "The virtuous woman" },
  { question: "Which of the apostles was a brother of John and was the first to be martyred by Herod?", options: ["James", "Peter", "Andrew", "Philip"], answer: "James" },
  { question: "What was the name of the priest of Midian who was the father-in-law of Moses?", options: ["Jethro", "Laban", "Potipherah", "Melchizedek"], answer: "Jethro" },
  { question: "Who was the man who survived the great flood with his wife, three sons, and their wives?", options: ["Noah", "Lot", "Enoch", "Methuselah"], answer: "Noah" },
  { question: "What was the name of the mountain where Elijah heard the 'still small voice' of God?", options: ["Mount Horeb", "Mount Carmel", "Mount Sinai", "Mount Nebo"], answer: "Mount Horeb" },
  { question: "In the book of Galatians, what is the 'fruit of the Spirit' listed first?", options: ["Love", "Joy", "Peace", "Faith"], answer: "Love" },
  { question: "Who was the high priest who raised Samuel in the temple?", options: ["Eli", "Phinehas", "Hophni", "Zadok"], answer: "Eli" },
  { question: "What was the name of the town where Jesus was raised?", options: ["Nazareth", "Bethlehem", "Jerusalem", "Capernaum"], answer: "Nazareth" },
  { question: "Which apostle was a citizen of Rome by birth?", options: ["Paul", "Peter", "John", "Matthew"], answer: "Paul" },
  { question: "What was the name of the wood used to build the Ark of the Covenant?", options: ["Shittim (Acacia)", "Gopher", "Cedar", "Olive"], answer: "Shittim (Acacia)" },
  { question: "Who was the wife of Isaac?", options: ["Rebekah", "Rachel", "Leah", "Sarah"], answer: "Rebekah" },
  { question: "Which book of the Bible follows the book of Jude?", options: ["Revelation", "Revelation", "1 John", "2 Peter"], answer: "Revelation" },
  { question: "What was the name of the city where the followers of Jesus were first called Christians?", options: ["Antioch", "Damascus", "Jerusalem", "Rome"], answer: "Antioch" },
  { question: "Who was the father of John the Baptist?", options: ["Zechariah", "Simeon", "Joachim", "Annas"], answer: "Zechariah" },
  { question: "What was the name of the mountain where Moses died?", options: ["Mount Nebo", "Mount Sinai", "Mount Hor", "Mount Carmel"], answer: "Mount Nebo" },
  { question: "Which disciple was a former tax collector?", options: ["Matthew", "Thomas", "Simon", "Andrew"], answer: "Matthew" },
  { question: "Who was the woman that was turned into a pillar of salt?", options: ["Lot's wife", "Sarah", "Rebekah", "Hagar"], answer: "Lot's wife" },
  { question: "What was the first plague God sent upon Egypt?", options: ["Water turned to blood", "Frogs", "Lice", "Darkness"], answer: "Water turned to blood" },
  { question: "How many books are in the New Testament?", options: ["27", "39", "66", "12"], answer: "27" },
  { question: "Who was the mother of John the Baptist?", options: ["Elizabeth", "Mary", "Hannah", "Sarah"], answer: "Elizabeth" },
  { question: "What is the shortest verse in the Bible?", options: ["Jesus wept.", "Rejoice evermore.", "God is love.", "Pray without ceasing."], answer: "Jesus wept." },
  { question: "How many days and nights did it rain during Noah's flood?", options: ["Forty", "Seven", "Twelve", "One hundred"], answer: "Forty" },
  { question: "Who was the man who survived being thrown into a den of lions?", options: ["Daniel", "Shadrach", "Meshach", "Abednego"], answer: "Daniel" },
  { question: "Who was the woman who hid the spies in Jericho?", options: ["Rahab", "Ruth", "Deborah", "Jael"], answer: "Rahab" },
  { question: "What is the final book of the Bible?", options: ["Revelation", "Jude", "3 John", "Malachi"], answer: "Revelation" },
  { question: "Who was the cousin of Jesus born to Elizabeth?", options: ["John the Baptist", "James", "Jude", "Andrew"], answer: "John the Baptist" },
  { question: "Which apostle was shipwrecked on Malta?", options: ["Paul", "Peter", "Barnabas", "John"], answer: "Paul" },
  { question: "How many tribes of Israel were there?", options: ["Twelve", "Ten", "Seven", "Forty"], answer: "Twelve" },
  { question: "Who was the high priest who raised Samuel?", options: ["Eli", "Samuel", "Aaron", "Zadok"], answer: "Eli}                                                                                         
];
