const bibleQuestions = [
  { question: "What Babylonian name was given to Daniel by the prince of the eunuchs?", options: ["Belteshazzar", "Belshazzar", "Abednego", "Beltheshar"], answer: "Belteshazzar", testament: "Old" },
  { question: "Which prophet was forbidden to mourn aloud when his wife died, as a sign to Israel?", options: ["Ezekiel", "Hosea", "Jeremiah", "Isaiah"], answer: "Ezekiel", testament: "Old" },
  { question: "Who was king of Salem and priest of the Most High God who blessed Abraham with bread and wine?", options: ["Melchizedek", "Adoni-zedek", "Abimelech", "Bera"], answer: "Melchizedek", testament: "Old" },
  { question: "How many Philistines did Shamgar slay with an ox goad (Judges 3:31)?", options: ["Six hundred", "Three hundred", "One thousand", "Eleven hundred"], answer: "Six hundred", testament: "Old" },
  { question: "Which left-handed judge slew Eglon king of Moab with a hidden dagger?", options: ["Ehud", "Othniel", "Shamgar", "Gideon"], answer: "Ehud", testament: "Old" },
  { question: "What was the name of the unfaithful wife the prophet Hosea was commanded to take?", options: ["Gomer", "Diblaim", "Bilhah", "Tamar"], answer: "Gomer", testament: "Old" },
  { question: "Which cupbearer to King Artaxerxes returned to rebuild Jerusalem's walls?", options: ["Nehemiah", "Ezra", "Zerubbabel", "Mordecai"], answer: "Nehemiah", testament: "Old" },
  { question: "By which brook did Elijah hide and was fed by ravens during the famine?", options: ["Cherith", "Kidron", "Jabbok", "Kishon"], answer: "Cherith", testament: "Old" },
  { question: "How many prophets of Baal did Elijah confront on Mount Carmel?", options: ["Four hundred and fifty", "Four hundred", "Eight hundred and fifty", "Nine hundred"], answer: "Four hundred and fifty", testament: "Old" },
  { question: "In what city was Cornelius the centurion stationed when Peter was sent to him?", options: ["Caesarea", "Joppa", "Damascus", "Antioch"], answer: "Caesarea", testament: "New" },
  { question: "Which prophet's scroll was the Ethiopian eunuch reading when Philip met him?", options: ["Isaiah", "Jeremiah", "Daniel", "The Psalms"], answer: "Isaiah", testament: "New" },
  { question: "What was the name given to the field bought with Judas Iscariot's thirty pieces of silver?", options: ["Akeldama", "Gehenna", "Tophet", "Gethsemane"], answer: "Akeldama", testament: "New" },
  { question: "In which city did Paul reason with the philosophers on Mars' Hill (the Areopagus) about the unknown god?", options: ["Athens", "Corinth", "Ephesus", "Berea"], answer: "Athens", testament: "New" },
  { question: "Which silversmith stirred up a riot against Paul over the goddess Diana?", options: ["Demetrius", "Alexander", "Tertullus", "Sosthenes"], answer: "Demetrius", testament: "New" },
  { question: "Which disciple did Peter raise from the dead in Joppa?", options: ["Tabitha (Dorcas)", "Eutychus", "Lydia", "Mary of Cleophas"], answer: "Tabitha (Dorcas)", testament: "New" },
  { question: "Who was the first of the twelve apostles to be martyred (slain by Herod with the sword)?", options: ["James the son of Zebedee", "Stephen", "Peter", "James the Lord's brother"], answer: "James the son of Zebedee", testament: "New" },
  { question: "From what city was Lydia, the seller of purple, whose heart the Lord opened in Philippi?", options: ["Thyatira", "Philippi", "Smyrna", "Laodicea"], answer: "Thyatira", testament: "New" },
  { question: "Who was compelled to bear the cross of Jesus on the way to Golgotha?", options: ["Simon of Cyrene", "Simon the Zealot", "Simon Peter", "Simon the Leper"], answer: "Simon of Cyrene", testament: "New" },
  { question: "What were the names of the two sons of Simon of Cyrene mentioned in Mark's Gospel?", options: ["Alexander and Rufus", "Andrew and Philip", "Cleopas and Clopas", "Lucius and Niger"], answer: "Alexander and Rufus", testament: "New" },
  { question: "Of the ten lepers Jesus cleansed, how many returned to give thanks?", options: ["One, a Samaritan", "Two", "Three", "None"], answer: "One, a Samaritan", testament: "New" },
  { question: "Which aged prophetess gave thanks in the temple at the presentation of the infant Jesus?", options: ["Anna", "Elisabeth", "Hannah", "Huldah"], answer: "Anna", testament: "New" },
  { question: "Of which tribe of Israel was the prophetess Anna (Luke 2:36)?", options: ["Asher", "Judah", "Levi", "Benjamin"], answer: "Asher", testament: "New" },
  { question: "Which archangel is said in the epistle of Jude to have contended with the devil over the body of Moses?", options: ["Michael", "Gabriel", "Raphael", "Uriel"], answer: "Michael", testament: "New" },
  { question: "Who was captain of King David's host for most of his reign?", options: ["Joab", "Benaiah", "Abner", "Ittai"], answer: "Joab", testament: "Old" },
  { question: "Whom did Solomon set over his army in the place of Joab?", options: ["Benaiah", "Adonijah", "Zadok", "Abishai"], answer: "Benaiah", testament: "Old" },
  { question: "How many wives and concubines did Solomon have, according to 1 Kings 11:3?", options: ["Seven hundred wives and three hundred concubines", "Three hundred wives and seven hundred concubines", "Five hundred wives and three hundred concubines", "One thousand wives in all"], answer: "Seven hundred wives and three hundred concubines", testament: "Old" },
  { question: "Which prophet tore his new garment into twelve pieces, foretelling the division of Solomon's kingdom?", options: ["Ahijah the Shilonite", "Shemaiah", "Iddo", "Nathan"], answer: "Ahijah the Shilonite", testament: "Old" },
  { question: "From which tribe was Saul, the first king of Israel?", options: ["Benjamin", "Judah", "Ephraim", "Manasseh"], answer: "Benjamin", testament: "Old" },
  { question: "Which queen of Judah destroyed all the seed royal and reigned six years until she was overthrown?", options: ["Athaliah", "Jezebel", "Maacah", "Bathsheba"], answer: "Athaliah", testament: "Old" },
  { question: "Who hid the infant king Joash in the temple for six years to save him from Athaliah?", options: ["Jehosheba", "Huldah", "Jehoaddan", "Zibiah"], answer: "Jehosheba", testament: "Old" },
  { question: "How many years in total did Jacob serve Laban for Leah and Rachel?", options: ["Fourteen", "Seven", "Twenty-one", "Twelve"], answer: "Fourteen", testament: "Old" },
  { question: "When Aaron's rod budded as a sign of his priestly authority, what did it bring forth?", options: ["Almonds", "Figs", "Olives", "Pomegranates"], answer: "Almonds", testament: "Old" },
  { question: "Which two sons of Aaron were consumed by fire for offering strange fire before the Lord?", options: ["Nadab and Abihu", "Eleazar and Ithamar", "Hophni and Phinehas", "Korah and Dathan"], answer: "Nadab and Abihu", testament: "Old" },
  { question: "How many sons of Sceva, a Jewish chief priest, attempted to cast out an evil spirit by the name of Jesus in Ephesus?", options: ["Seven", "Three", "Five", "Twelve"], answer: "Seven", testament: "New" },
  { question: "Before which Roman governor did Paul utter the words, 'I appeal unto Caesar'?", options: ["Festus", "Felix", "Pilate", "Gallio"], answer: "Festus", testament: "New" },
  { question: "Which son of David declared himself king while David was still alive?", options: ["Absalom", "Adonijah", "Solomon", "Amnon"], answer: "Adonijah", testament: "Old" },
  { question: "Who was struck with leprosy after unlawfully burning incense in the temple?", options: ["Uzziah", "Ahaz", "Jotham", "Hezekiah"], answer: "Uzziah", testament: "Old" },
  { question: "Which king of Judah began to reign at age eight?", options: ["Josiah", "Joash", "Manasseh", "Hezekiah"], answer: "Josiah", testament: "Old" },
  { question: "Which prophet confronted David over Bathsheba?", options: ["Nathan", "Samuel", "Gad", "Elijah"], answer: "Nathan", testament: "Old" },
  { question: "Who fell from a third-story window while Paul was preaching at Troas?", options: ["Eutychus", "Tychicus", "Silas", "Timothy"], answer: "Eutychus", testament: "New" },
  { question: "Who was chosen by lot to replace Judas Iscariot among the twelve apostles?", options: ["Matthias", "Barnabas", "Stephen", "Philip"], answer: "Matthias", testament: "New" },
  { question: "In which city was the apostle Paul born?", options: ["Antioch", "Tarsus", "Damascus", "Jerusalem"], answer: "Tarsus", testament: "New" },
  { question: "On which Mediterranean island was Paul shipwrecked en route to Rome?", options: ["Crete", "Cyprus", "Malta", "Patmos"], answer: "Malta", testament: "New" },
  { question: "Which figure walked with God and 'was not, for God took him' before the flood?", options: ["Enoch", "Noah", "Methuselah", "Lamech"], answer: "Enoch", testament: "Old" },
  { question: "Who appeared with Jesus on the Mount of Transfiguration?", options: ["Elijah and Moses", "Elijah and Isaiah", "Moses and Abraham", "David and Elijah"], answer: "Elijah and Moses", testament: "New" },
  { question: "Which judge slew a thousand Philistines with the jawbone of a donkey?", options: ["Samson", "Gideon", "Jephthah", "Ehud"], answer: "Samson", testament: "Old" },
  { question: "Which disciple confessed 'My Lord and my God' after touching Jesus' wounds?", options: ["Thomas", "Peter", "John", "James"], answer: "Thomas", testament: "New" },
  { question: "Who was the first Christian martyr, stoned while seeing the heavens opened?", options: ["Stephen", "James", "Peter", "Paul"], answer: "Stephen", testament: "New" },
  { question: "Who was Paul's first missionary partner, sent out from Antioch in Acts 13?", options: ["Barnabas", "Silas", "Timothy", "Luke"], answer: "Barnabas", testament: "New" },
  { question: "Who were struck dead for lying to the Holy Spirit about the price of land?", options: ["Both Ananias and Sapphira", "Ananias only", "Sapphira only", "Simon and Sapphira"], answer: "Both Ananias and Sapphira", testament: "New" },
  { question: "Which two high priests are named in connection with the trial of Jesus?", options: ["Annas and Caiaphas", "Annas and Eleazar", "Caiaphas and Theophilus", "Caiaphas and Ananias"], answer: "Annas and Caiaphas", testament: "New" },
  { question: "For how many pieces of silver was Joseph sold by his brothers?", options: ["Twenty", "Thirty", "Fifty", "Seventy"], answer: "Twenty", testament: "Old" },
  { question: "Who fashioned the golden calf at Mount Sinai while Moses was on the mountain?", options: ["Aaron", "Hur", "Joshua", "Caleb"], answer: "Aaron", testament: "Old" },
  { question: "With whom did Jacob wrestle until daybreak at Peniel?", options: ["A man (later identified as God)", "Esau", "An unnamed Egyptian", "An angel of Pharaoh"], answer: "A man (later identified as God)", testament: "Old" },
  { question: "In Genesis 28, what did Jacob see in his dream at Bethel?", options: ["A ladder reaching to heaven", "A burning altar", "A sealed scroll", "A field of wheat"], answer: "A ladder reaching to heaven", testament: "Old" },
  { question: "Which disciple was a tax collector before being called by Jesus?", options: ["Matthew", "Peter", "Philip", "James"], answer: "Matthew", testament: "New" },
  { question: "Who was the disciple Jesus loved, traditionally identified as the author of the Fourth Gospel?", options: ["John", "Peter", "James", "Andrew"], answer: "John", testament: "New" },
  { question: "How was Elijah taken up into heaven?", options: ["By a chariot of fire and a whirlwind", "In a cloud of glory", "By an angelic escort", "In a vision of light"], answer: "By a chariot of fire and a whirlwind", testament: "Old" },
  { question: "Who was Elisha's prophetic mentor before he received a double portion of his spirit?", options: ["Elijah", "Samuel", "Isaiah", "Nathan"], answer: "Elijah", testament: "Old" },
  { question: "Which apostle, exiled to Patmos, received the visions recorded in the book of Revelation?", options: ["John", "Peter", "Paul", "James"], answer: "John", testament: "New" },
  { question: "What was the name of Moses' wife, the daughter of the priest of Midian?", options: ["Zipporah", "Miriam", "Asenath", "Keturah"], answer: "Zipporah", testament: "Old" },
  { question: "Who was the father-in-law of Moses, also called Reuel?", options: ["Jethro", "Hobab", "Laban", "Jesse"], answer: "Jethro", testament: "Old" },
  { question: "Who was the priestly father of John the Baptist, struck dumb until John's naming?", options: ["Zacharias", "Eli", "Joachim", "Zechariah son of Berechiah"], answer: "Zacharias", testament: "New" },
  { question: "Of which priestly course was Zacharias, the father of John the Baptist (Luke 1:5)?", options: ["Abia", "Aaron", "Eleazar", "Jeshua"], answer: "Abia", testament: "New" },
  { question: "Which two wicked sons of Eli the priest died on the same day when the ark was taken?", options: ["Hophni and Phinehas", "Nadab and Abihu", "Joel and Abiah", "Mahlon and Chilion"], answer: "Hophni and Phinehas", testament: "Old" },
  { question: "Where did King Saul go in disguise to consult a woman with a familiar spirit on the eve of his death?", options: ["Endor", "Shiloh", "Gilgal", "Beersheba"], answer: "Endor", testament: "Old" },
  { question: "When Samuel sought Saul to make him king, where had Saul hidden himself?", options: ["Among the stuff (baggage)", "In a cave at Adullam", "In his father's house", "Behind the threshing floor"], answer: "Among the stuff (baggage)", testament: "Old" },
  { question: "Who was the mother of Samuel the prophet, who had vowed her son to the Lord?", options: ["Hannah", "Peninnah", "Elisheba", "Jochebed"], answer: "Hannah", testament: "Old" },
  { question: "Which king of Judah tore his clothes when the book of the law was read to him?", options: ["Josiah", "Hezekiah", "Manasseh", "Jehoshaphat"], answer: "Josiah", testament: "Old" },
  { question: "Which prophetess did King Josiah send his servants to inquire of the LORD?", options: ["Huldah", "Deborah", "Miriam", "Anna"], answer: "Huldah", testament: "Old" },
  { question: "Which king of Babylon saw the handwriting on the wall on the night his kingdom fell?", options: ["Belshazzar", "Nebuchadnezzar", "Darius", "Evil-merodach"], answer: "Belshazzar", testament: "Old" },
  { question: "Which Persian king took Esther as his queen?", options: ["Ahasuerus", "Cyrus", "Artaxerxes", "Darius"], answer: "Ahasuerus", testament: "Old" },
  { question: "Who was Esther's older cousin who raised her as his own daughter?", options: ["Mordecai", "Hegai", "Memucan", "Bigthan"], answer: "Mordecai", testament: "Old" },
  { question: "Which Agagite official sought to destroy all the Jews in Persia?", options: ["Haman", "Hegai", "Memucan", "Bigthan"], answer: "Haman", testament: "Old" },
  { question: "How many provinces did King Ahasuerus rule from India unto Ethiopia?", options: ["One hundred and twenty-seven", "One hundred and twenty", "Seventy", "Twelve"], answer: "One hundred and twenty-seven", testament: "Old" },
  { question: "In what palace city of Persia did Queen Esther reside?", options: ["Shushan", "Babylon", "Ecbatana", "Persepolis"], answer: "Shushan", testament: "Old" },
  { question: "How many souls were saved through the waters of the flood in Noah's ark (1 Peter 3:20)?", options: ["Eight", "Six", "Ten", "Twelve"], answer: "Eight", testament: "Old" },
  { question: "To what land did Cain go to dwell after slaying his brother Abel?", options: ["Nod", "Shinar", "Havilah", "Cush"], answer: "Nod", testament: "Old" },
  { question: "From what city did the LORD call Abram before he came into Canaan?", options: ["Ur of the Chaldees", "Haran", "Salem", "Beersheba"], answer: "Ur of the Chaldees", testament: "Old" },
  { question: "What was the name of Joseph's Egyptian wife, given to him by Pharaoh?", options: ["Asenath", "Zipporah", "Bithiah", "Tahpenes"], answer: "Asenath", testament: "Old" },
  { question: "Which of Joseph's brothers did he bind and keep in Egypt as surety?", options: ["Simeon", "Reuben", "Judah", "Benjamin"], answer: "Simeon", testament: "Old" },
  { question: "On which mountain did Moses die after viewing the Promised Land?", options: ["Mount Nebo", "Mount Hor", "Mount Sinai", "Mount Pisgah's peak Carmel"], answer: "Mount Nebo", testament: "Old" },
  { question: "How old was Moses when he died (Deuteronomy 34:7)?", options: ["One hundred and twenty", "One hundred", "Eighty", "One hundred and ten"], answer: "One hundred and twenty", testament: "Old" },
  { question: "Which judge made a rash vow that cost him his only daughter after defeating the Ammonites?", options: ["Jephthah", "Gideon", "Samson", "Abimelech"], answer: "Jephthah", testament: "Old" },
  { question: "Over which city did Joshua command the sun to stand still in the day of battle?", options: ["Gibeon", "Ai", "Jericho", "Hebron"], answer: "Gibeon", testament: "Old" },
  { question: "Who was the Jewess wife of Felix the Roman governor before whom Paul reasoned?", options: ["Drusilla", "Bernice", "Damaris", "Claudia"], answer: "Drusilla", testament: "New" },
  { question: "Who was the sister of King Agrippa II who attended Paul's hearing at Caesarea?", options: ["Bernice", "Drusilla", "Herodias", "Salome"], answer: "Bernice", testament: "New" },
  { question: "In which city was Paul stoned and dragged out of the city as though dead?", options: ["Lystra", "Iconium", "Derbe", "Antioch of Pisidia"], answer: "Lystra", testament: "New" },
  { question: "Apollos, the eloquent and mighty in the Scriptures, was a Jew born in what city?", options: ["Alexandria", "Antioch", "Tarsus", "Cyrene"], answer: "Alexandria", testament: "New" },
  { question: "Whom did Paul send back to his master, beseeching him to receive him as a brother?", options: ["Onesimus to Philemon", "Tychicus to Philemon", "Onesimus to Philippi", "Epaphras to Colosse"], answer: "Onesimus to Philemon", testament: "New" },
  { question: "Which book closes the Old Testament canon?", options: ["Malachi", "Zechariah", "Nehemiah", "Chronicles"], answer: "Malachi", testament: "Old" },
  { question: "How many plagues did the LORD send upon Egypt before Pharaoh let Israel go?", options: ["Ten", "Seven", "Twelve", "Forty"], answer: "Ten", testament: "Old" },
  { question: "How many devils did Jesus cast out of Mary Magdalene?", options: ["Seven", "Three", "Twelve", "Five"], answer: "Seven", testament: "New" },
  { question: "In what river was Jesus baptized of John?", options: ["Jordan", "Kidron", "Jabbok", "Galilee"], answer: "Jordan", testament: "New" },
  { question: "How many days did Jesus fast in the wilderness when tempted of the devil?", options: ["Forty", "Three", "Seven", "Thirty"], answer: "Forty", testament: "New" },
  { question: "What was the name of the high priest's servant whose ear Peter cut off?", options: ["Malchus", "Tertius", "Secundus", "Onesiphorus"], answer: "Malchus", testament: "New" },
  { question: "By what pool with five porches did Jesus heal a man who had been infirm thirty-eight years?", options: ["Bethesda", "Siloam", "Gihon", "En-rogel"], answer: "Bethesda", testament: "New" },
  { question: "To what pool did Jesus send the man born blind to wash and receive sight?", options: ["Siloam", "Bethesda", "Gihon", "Jordan"], answer: "Siloam", testament: "New" },
  { question: "How many great fishes did the disciples draw to land in the net after the resurrection (John 21)?", options: ["A hundred and fifty and three", "Five thousand", "Seventy", "Twelve"], answer: "A hundred and fifty and three", testament: "New" },
  { question: "About how many souls were added to the church on the day of Pentecost?", options: ["Three thousand", "Five thousand", "One hundred and twenty", "Seven thousand"], answer: "Three thousand", testament: "New" }
];
